
######################db CONNECTION###########################################################
require(odbc)
source("DBConnection.R")
db <- openDBConnection()

#######################Queries for Program Review###########################################################

#get Distinct Headcount data from the database for a PROGRAM
progDistinctHC <- function(program, minTermSort, maxTermSort) {
  
  qDistinctHC <- sprintf("SELECT ACADEMIC_YEAR, PROGRAM, DEPARTMENT, COUNT(DISTINCT ENR_STUDENT_ID) HEADCOUNT
  FROM(SELECT TER_SORT, ENR_TERM, 
  CASE 
	WHEN RIGHT(TER_SORT, 1) < '3' THEN LEFT(TER_SORT,4) - 1
	ELSE LEFT(TER_SORT, 4)
	END AS ACADEMIC_YEAR,
  DEC_DESC AS PROGRAM,
  DEP_DESC AS DEPARTMENT,
  ENR_STUDENT_ID
  FROM ENROLLMENT
  INNER JOIN SECTION ON ENR_SECTION_ID = SECTION_ID
  INNER JOIN COURSE ON SEC_COURSE_ID = COURSE_ID
  INNER JOIN DEPARTMENT ON CRS_DEPARTMENT = DEPARTMENT_ID
  INNER JOIN DEPT_CHAIR ON DEP_DEPT_CHAIR = DEPT_CHAIR_ID
  INNER JOIN STUDENT ON ENR_STUDENT_ID = STUDENT_ID
  INNER JOIN TERM ON ENR_TERM = TERM_ID
  WHERE DEPT_CHAIR_ID = '%s'
  AND TER_SORT between '%s' and '%s'
  AND (ENR_CENSUS_REG_FLAG = 'Y' OR ENR_CURRENT_REG_FLAG = 'Y')) STUDENTS
  GROUP BY ACADEMIC_YEAR, PROGRAM, DEPARTMENT"
                         , program
                         , minTermSort
                         , maxTermSort
  )
  DistinctHC <- dbGetQuery(db, qDistinctHC)
  return(DistinctHC)
}

#get Distinct Headcount data from the database for a PROGRAM in Total
progDistinctHCTot <- function(program, minTermSort, maxTermSort) {
  
  qDistinctHC <- sprintf("SELECT ACADEMIC_YEAR, 'Program Total' PROGRAM, COUNT(DISTINCT ENR_STUDENT_ID) HEADCOUNT
  FROM(SELECT TER_SORT, ENR_TERM, 
  CASE 
	WHEN RIGHT(TER_SORT, 1) < '3' THEN LEFT(TER_SORT,4) - 1
	ELSE LEFT(TER_SORT, 4)
	END AS ACADEMIC_YEAR,
  DEC_DESC AS PROGRAM,
  DEP_DESC AS DEPARTMENT,
  ENR_STUDENT_ID
  FROM ENROLLMENT
  INNER JOIN SECTION ON ENR_SECTION_ID = SECTION_ID
  INNER JOIN COURSE ON SEC_COURSE_ID = COURSE_ID
  INNER JOIN DEPARTMENT ON CRS_DEPARTMENT = DEPARTMENT_ID
  INNER JOIN DEPT_CHAIR ON DEP_DEPT_CHAIR = DEPT_CHAIR_ID
  INNER JOIN STUDENT ON ENR_STUDENT_ID = STUDENT_ID
  INNER JOIN TERM ON ENR_TERM = TERM_ID
  WHERE DEPT_CHAIR_ID = '%s'
  AND TER_SORT between '%s' and '%s'
  AND (ENR_CENSUS_REG_FLAG = 'Y' OR ENR_CURRENT_REG_FLAG = 'Y')) STUDENTS
  GROUP BY ACADEMIC_YEAR, PROGRAM"
                         , program
                         , minTermSort
                         , maxTermSort
  )
  DistinctHC <- dbGetQuery(db, qDistinctHC)
  return(DistinctHC)
}


#get Distinct Headcount from the database for the College
distinctHCCol <- function(minTermSort, maxTermSort) {
  
  qDistinctHC <- sprintf("SELECT ACADEMIC_YEAR, 'Butte College' PROGRAM, COUNT(DISTINCT ENR_STUDENT_ID) HEADCOUNT
  FROM(SELECT TER_SORT, ENR_TERM, 
  CASE 
	WHEN RIGHT(TER_SORT, 1) < '3' THEN LEFT(TER_SORT,4) - 1
	ELSE LEFT(TER_SORT, 4)
	END AS ACADEMIC_YEAR,
	ENR_STUDENT_ID
  FROM ENROLLMENT
  INNER JOIN SECTION ON ENR_SECTION_ID = SECTION_ID
  INNER JOIN COURSE ON SEC_COURSE_ID = COURSE_ID
  INNER JOIN STUDENT ON ENR_STUDENT_ID = STUDENT_ID
  INNER JOIN TERM ON ENR_TERM = TERM_ID
  WHERE TER_SORT between '%s' and '%s'
  AND (ENR_CENSUS_REG_FLAG = 'Y' OR ENR_CURRENT_REG_FLAG = 'Y')) STUDENTS
  GROUP BY ACADEMIC_YEAR"
                         , minTermSort
                         , maxTermSort
  )
  DistinctHC <- dbGetQuery(db, qDistinctHC)
  return(DistinctHC)
}

#get gender data from the database for a PROGRAM
progPercentGender <- function(program, minTermSort, maxTermSort) {

  qGender <- sprintf("SELECT ACADEMIC_YEAR, PROGRAM, DEPARTMENT, STU_GENDER, COUNT(DISTINCT ENR_STUDENT_ID) HEADCOUNT
  FROM(SELECT
    CASE 
	  WHEN RIGHT(TER_SORT, 1) < '3' THEN LEFT(TER_SORT,4) - 1
	  ELSE LEFT(TER_SORT, 4)
	  END AS ACADEMIC_YEAR,
    DEC_DESC AS PROGRAM,
    DEP_DESC AS DEPARTMENT,
    CASE
	  WHEN STU_GENDER IS NULL OR STU_GENDER IN(' ', 'U', 'X', 'B') THEN 'U'
	  ELSE STU_GENDER
	  END AS STU_GENDER,
    ENR_STUDENT_ID
    FROM ENROLLMENT
    INNER JOIN SECTION ON ENR_SECTION_ID = SECTION_ID
    INNER JOIN COURSE ON SEC_COURSE_ID = COURSE_ID
    INNER JOIN DEPARTMENT ON CRS_DEPARTMENT = DEPARTMENT_ID
    INNER JOIN DEPT_CHAIR ON DEP_DEPT_CHAIR = DEPT_CHAIR_ID
    INNER JOIN STUDENT ON ENR_STUDENT_ID = STUDENT_ID
    INNER JOIN TERM ON ENR_TERM = TERM_ID
    WHERE DEPT_CHAIR_ID = '%s'
    AND TER_SORT between '%s' and '%s'
    AND (ENR_CENSUS_REG_FLAG = 'Y' OR ENR_CURRENT_REG_FLAG = 'Y')) GENDER
  GROUP BY ACADEMIC_YEAR, PROGRAM, DEPARTMENT, STU_GENDER"
                     , program
                     , minTermSort
                     , maxTermSort
)
  genDf <- dbGetQuery(db, qGender)
  return(genDf)
}

#get gender data from the database for a PROGRAM TOTAL
progPercentGenderTot <- function(program, minTermSort, maxTermSort) {
  
  qGender <- sprintf("SELECT ACADEMIC_YEAR, PROGRAM, STU_GENDER, COUNT(DISTINCT ENR_STUDENT_ID) HEADCOUNT
  FROM(SELECT
    CASE 
	  WHEN RIGHT(TER_SORT, 1) < '3' THEN LEFT(TER_SORT,4) - 1
	  ELSE LEFT(TER_SORT, 4)
	  END AS ACADEMIC_YEAR,
    DEC_DESC AS PROGRAM,
    CASE
	  WHEN STU_GENDER IS NULL OR STU_GENDER IN(' ', 'U', 'X', 'B') THEN 'U'
	  ELSE STU_GENDER
	  END AS STU_GENDER,
    ENR_STUDENT_ID
    FROM ENROLLMENT
    INNER JOIN SECTION ON ENR_SECTION_ID = SECTION_ID
    INNER JOIN COURSE ON SEC_COURSE_ID = COURSE_ID
    INNER JOIN DEPARTMENT ON CRS_DEPARTMENT = DEPARTMENT_ID
    INNER JOIN DEPT_CHAIR ON DEP_DEPT_CHAIR = DEPT_CHAIR_ID
    INNER JOIN STUDENT ON ENR_STUDENT_ID = STUDENT_ID
    INNER JOIN TERM ON ENR_TERM = TERM_ID
    WHERE DEPT_CHAIR_ID = '%s'
    AND TER_SORT between '%s' and '%s'
    AND (ENR_CENSUS_REG_FLAG = 'Y' OR ENR_CURRENT_REG_FLAG = 'Y')) GENDER
  GROUP BY ACADEMIC_YEAR, PROGRAM, STU_GENDER"
                     , program
                     , minTermSort
                     , maxTermSort
  )
  genDf <- dbGetQuery(db, qGender)
  return(genDf)
}


#get gender data from the database for the College
percentGenderCol <- function(minTermSort, maxTermSort) {
  
  qGender <- sprintf("SELECT ACADEMIC_YEAR, 'Butte College' PROGRAM, STU_GENDER, COUNT(DISTINCT ENR_STUDENT_ID) HEADCOUNT
  FROM (SELECT TER_SORT, ENR_TERM, 
    CASE 
	  WHEN RIGHT(TER_SORT, 1) < '3' THEN LEFT(TER_SORT,4) - 1
	  ELSE LEFT(TER_SORT, 4)
	  END AS ACADEMIC_YEAR,
    CASE
	  WHEN STU_GENDER IS NULL OR STU_GENDER IN(' ', 'U', 'X', 'B') THEN 'U'
	  ELSE STU_GENDER
	  END AS STU_GENDER,
	  ENR_STUDENT_ID 
    FROM ENROLLMENT
    INNER JOIN SECTION ON ENR_SECTION_ID = SECTION_ID
    INNER JOIN COURSE ON SEC_COURSE_ID = COURSE_ID
    INNER JOIN STUDENT ON ENR_STUDENT_ID = STUDENT_ID
    INNER JOIN TERM ON ENR_TERM = TERM_ID
    WHERE TER_SORT between '%s' and '%s'
    AND (ENR_CENSUS_REG_FLAG = 'Y' OR ENR_CURRENT_REG_FLAG = 'Y')) COLGENDER
  GROUP BY ACADEMIC_YEAR, STU_GENDER
  ORDER BY 1, 2"
                     , minTermSort
                     , maxTermSort
  )
  genDf <- dbGetQuery(db, qGender)
  return(genDf)
}

#Demographics - Ethnicity
#get ethnicity data from the database for a PROGRAM
progPercentEthnicity <- function(program, minTermSort, maxTermSort) {
  
  qEthnicity <- sprintf("SELECT ACADEMIC_YEAR, DEPARTMENT, ETI_DESC, COUNT(DISTINCT ETHNICITY.ENR_STUDENT_ID) HEADCOUNT
FROM (SELECT DISTINCT TER_SORT, ENR_TERM, 
  CASE 
	WHEN RIGHT(TER_SORT, 1) < '3' THEN LEFT(TER_SORT,4) - 1
	ELSE LEFT(TER_SORT, 4)
	END AS ACADEMIC_YEAR,
	DEC_DESC AS PROGRAM,
	DEP_DESC AS DEPARTMENT,
	ETI_DESC,
	ENR_STUDENT_ID
  FROM ENROLLMENT
  INNER JOIN SECTION ON ENR_SECTION_ID = SECTION_ID
  INNER JOIN COURSE ON SEC_COURSE_ID = COURSE_ID
  INNER JOIN DEPARTMENT ON CRS_DEPARTMENT = DEPARTMENT_ID
  INNER JOIN DEPT_CHAIR ON DEP_DEPT_CHAIR = DEPT_CHAIR_ID
  INNER JOIN STUDENT ON ENR_STUDENT_ID = STUDENT_ID
  LEFT JOIN ETHNICITY_IPEDS ON STU_ETHNICITY_IPEDS = ETHNICITY_IPEDS_ID
  INNER JOIN TERM ON ENR_TERM = TERM_ID
  WHERE DEPT_CHAIR_ID = '%s'
  AND TER_SORT between '%s' and '%s'
  AND (ENR_CENSUS_REG_FLAG = 'Y' OR ENR_CURRENT_REG_FLAG = 'Y')) ETHNICITY
 GROUP BY ACADEMIC_YEAR, DEPARTMENT, ETI_DESC"
                        , program
                        , minTermSort
                        , maxTermSort
  )
  ethDf <- dbGetQuery(db, qEthnicity)
  return(ethDf)
}

#get Ethnicity data from the database for a PROGRAM TOTAL
progPercentEthnicityTot <- function(program, minTermSort, maxTermSort) {
  
  qEthnicity <- sprintf("SELECT ACADEMIC_YEAR, PROGRAM, ETI_DESC, COUNT(DISTINCT ETHNICITY.ENR_STUDENT_ID) HEADCOUNT
FROM (SELECT DISTINCT TER_SORT, ENR_TERM, 
  CASE 
	WHEN RIGHT(TER_SORT, 1) < '3' THEN LEFT(TER_SORT,4) - 1
	ELSE LEFT(TER_SORT, 4)
	END AS ACADEMIC_YEAR,
	DEC_DESC AS PROGRAM,
	DEP_DESC AS DEPARTMENT,
	ETI_DESC,
	ENR_STUDENT_ID
  FROM ENROLLMENT
  INNER JOIN SECTION ON ENR_SECTION_ID = SECTION_ID
  INNER JOIN COURSE ON SEC_COURSE_ID = COURSE_ID
  INNER JOIN DEPARTMENT ON CRS_DEPARTMENT = DEPARTMENT_ID
  INNER JOIN DEPT_CHAIR ON DEP_DEPT_CHAIR = DEPT_CHAIR_ID
  INNER JOIN STUDENT ON ENR_STUDENT_ID = STUDENT_ID
  LEFT JOIN ETHNICITY_IPEDS ON STU_ETHNICITY_IPEDS = ETHNICITY_IPEDS_ID
  INNER JOIN TERM ON ENR_TERM = TERM_ID
  WHERE DEPT_CHAIR_ID = '%s'
  AND TER_SORT between '%s' and '%s'
  AND (ENR_CENSUS_REG_FLAG = 'Y' OR ENR_CURRENT_REG_FLAG = 'Y')) ETHNICITY
 GROUP BY ACADEMIC_YEAR, PROGRAM, ETI_DESC"
                     , program
                     , minTermSort
                     , maxTermSort
  )
  ethDf <- dbGetQuery(db, qEthnicity)
  return(ethDf)
}


#get ethnicity data from the database for the College
percentEthnicityCol <- function(minTermSort, maxTermSort) {
  
  qEthnicity <- sprintf("SELECT ACADEMIC_YEAR, 'Butte College' PROGRAM, ETI_DESC, COUNT(DISTINCT ETHNICITY.ENR_STUDENT_ID) HEADCOUNT
FROM (SELECT DISTINCT TER_SORT, ENR_TERM, 
  CASE 
	WHEN RIGHT(TER_SORT, 1) < '3' THEN LEFT(TER_SORT,4) - 1
	ELSE LEFT(TER_SORT, 4)
	END AS ACADEMIC_YEAR,
	ETI_DESC,  
	ENR_STUDENT_ID
  FROM ENROLLMENT
  INNER JOIN SECTION ON ENR_SECTION_ID = SECTION_ID
  INNER JOIN COURSE ON SEC_COURSE_ID = COURSE_ID
  INNER JOIN STUDENT ON ENR_STUDENT_ID = STUDENT_ID
  LEFT JOIN ETHNICITY_IPEDS ON STU_ETHNICITY_IPEDS = ETHNICITY_IPEDS_ID
  INNER JOIN TERM ON ENR_TERM = TERM_ID
  WHERE TER_SORT between '%s' and '%s'
  AND (ENR_CENSUS_REG_FLAG = 'Y' OR ENR_CURRENT_REG_FLAG = 'Y')) ETHNICITY
 GROUP BY ACADEMIC_YEAR, ETI_DESC"
                        , minTermSort
                        , maxTermSort
  )
  ethDf <- dbGetQuery(db, qEthnicity)
  return(ethDf)
}

#Demographics - Age
#get age data from the database for a PROGRAM

progPercentAge <- function(program, minTermSort, maxTermSort) {
  
  qAge <- sprintf("SELECT TER_SORT, ENR_TERM,
  CASE 
	WHEN STT_AGE BETWEEN '0' AND '17' THEN '17 and Under'
	WHEN STT_AGE BETWEEN '18' AND '20' THEN '18 - 20'
	WHEN STT_AGE BETWEEN '21' AND '25' THEN '21 - 25'	
	WHEN STT_AGE BETWEEN '26' AND '39' THEN '26 - 39'
	WHEN STT_AGE BETWEEN '40' AND '59' THEN '40 - 59'
	WHEN STT_AGE >= '60' THEN '60+'
	ELSE 'Unknown'
	END AS AGE,
	DEC_DESC AS PROGRAM,
  DEP_DESC AS DEPARTMENT,
	COUNT (DISTINCT ENR_STUDENT_ID) HEADCOUNT
  FROM ENROLLMENT
  INNER JOIN SECTION ON ENR_SECTION_ID = SECTION_ID
  INNER JOIN COURSE ON SEC_COURSE_ID = COURSE_ID
  INNER JOIN DEPARTMENT ON CRS_DEPARTMENT = DEPARTMENT_ID
  INNER JOIN DEPT_CHAIR ON DEP_DEPT_CHAIR = DEPT_CHAIR_ID
  INNER JOIN STUDENT ON ENR_STUDENT_ID = STUDENT_ID
  INNER JOIN STUDENT_TERM ON ENR_STUDENT_ID = STT_STUDENT_ID
  AND ENR_TERM = STT_TERM
  INNER JOIN TERM ON ENR_TERM = TERM_ID
  WHERE DEPT_CHAIR_ID = '%s'
  AND TER_SORT between '%s' and '%s'
  AND (ENR_CENSUS_REG_FLAG = 'Y' OR ENR_CURRENT_REG_FLAG = 'Y')
  AND ENR_TERM LIKE '%%FA'  
  GROUP BY TER_SORT, ENR_TERM, STT_AGE, DEP_DESC, DEC_DESC
  ORDER BY TER_SORT, DEC_DESC, STT_AGE"
                  , program
                  , minTermSort
                  , maxTermSort
  )
  ageDf <- dbGetQuery(db, qAge)
  return(ageDf)
}

#get age data from the database for a PROGRAM TOTAL
progPercentAgeTot <- function(program, minTermSort, maxTermSort) {
  
  qAge <- sprintf("SELECT TER_SORT, ENR_TERM,
  CASE 
	WHEN STT_AGE BETWEEN '0' AND '17' THEN '17 and Under'
	WHEN STT_AGE BETWEEN '18' AND '20' THEN '18 - 20'
	WHEN STT_AGE BETWEEN '21' AND '25' THEN '21 - 25'	
	WHEN STT_AGE BETWEEN '26' AND '39' THEN '26 - 39'
	WHEN STT_AGE BETWEEN '40' AND '59' THEN '40 - 59'
	WHEN STT_AGE >= '60' THEN '60+'
	ELSE 'Unknown'
	END AS AGE,
  DEC_DESC AS PROGRAM,	
	COUNT (DISTINCT ENR_STUDENT_ID) HEADCOUNT
  FROM ENROLLMENT
  INNER JOIN SECTION ON ENR_SECTION_ID = SECTION_ID
  INNER JOIN COURSE ON SEC_COURSE_ID = COURSE_ID
  INNER JOIN DEPARTMENT ON CRS_DEPARTMENT = DEPARTMENT_ID
  INNER JOIN DEPT_CHAIR ON DEP_DEPT_CHAIR = DEPT_CHAIR_ID
  INNER JOIN STUDENT ON ENR_STUDENT_ID = STUDENT_ID
  INNER JOIN STUDENT_TERM ON ENR_STUDENT_ID = STT_STUDENT_ID
  AND ENR_TERM = STT_TERM
  INNER JOIN TERM ON ENR_TERM = TERM_ID
  WHERE DEPT_CHAIR_ID = '%s'
  AND TER_SORT between '%s' and '%s'
  AND (ENR_CENSUS_REG_FLAG = 'Y' OR ENR_CURRENT_REG_FLAG = 'Y')
  AND ENR_TERM LIKE '%%FA'  
  GROUP BY TER_SORT, ENR_TERM, STT_AGE, DEC_DESC
  ORDER BY TER_SORT, DEC_DESC, STT_AGE"
                  , program
                  , minTermSort
                  , maxTermSort
  )
  ageDf <- dbGetQuery(db, qAge)
  return(ageDf)
}


#get AGE data from the database for the College
percentAgeCol <- function(minTermSort, maxTermSort) {
  
  qAge <- sprintf("SELECT TER_SORT, ENR_TERM, 
  CASE 
	WHEN STT_AGE BETWEEN '0' AND '17' THEN '17 and Under'
	WHEN STT_AGE BETWEEN '18' AND '20' THEN '18 - 20'
	WHEN STT_AGE BETWEEN '21' AND '25' THEN '21 - 25'	
	WHEN STT_AGE BETWEEN '26' AND '39' THEN '26 - 39'
	WHEN STT_AGE BETWEEN '40' AND '59' THEN '40 - 59'
	WHEN STT_AGE >= '60' THEN '60+'
	ELSE 'Unknown'
	END AS AGE,
	'Butte College' PROGRAM,
	COUNT (DISTINCT ENR_STUDENT_ID) HEADCOUNT
  FROM ENROLLMENT
  INNER JOIN SECTION ON ENR_SECTION_ID = SECTION_ID
  INNER JOIN COURSE ON SEC_COURSE_ID = COURSE_ID
  INNER JOIN STUDENT ON ENR_STUDENT_ID = STUDENT_ID
  INNER JOIN STUDENT_TERM ON ENR_STUDENT_ID = STT_STUDENT_ID
  AND ENR_TERM = STT_TERM
  INNER JOIN TERM ON ENR_TERM = TERM_ID
  WHERE TER_SORT between '%s' and '%s'
  AND (ENR_CENSUS_REG_FLAG = 'Y' OR ENR_CURRENT_REG_FLAG = 'Y')
  AND ENR_TERM LIKE '%%FA'  
  GROUP BY TER_SORT, ENR_TERM, STT_AGE
  ORDER BY TER_SORT, STT_AGE"
                  , minTermSort
                  , maxTermSort
  )
  ageDf <- dbGetQuery(db, qAge)
  return(ageDf)
}

#get Low Income data from the database for a PROGRAM
progPercentLow <- function(program, minTermSort, maxTermSort) {
  
  qLow <- sprintf("SELECT ENR_TERM, DEPARTMENT, LOW_INCOME, COUNT(DISTINCT ENR_STUDENT_ID) HEADCOUNT
FROM (SELECT TER_SORT, ENR_TERM, 
  CASE 
	WHEN RIGHT(TER_SORT, 1) < '3' THEN LEFT(TER_SORT,4) - 1
	ELSE LEFT(TER_SORT, 4)
	END AS ACADEMIC_YEAR,
  DEC_DESC AS PROGRAM,
  DEP_DESC AS DEPARTMENT,
  ENR_STUDENT_ID,
  CASE 
	WHEN LOW_INCOME.SFA_STUDENT_ID IS NOT NULL THEN 'Y'
	ELSE 'N'
	END AS LOW_INCOME
  FROM ENROLLMENT
  INNER JOIN SECTION ON ENR_SECTION_ID = SECTION_ID
  INNER JOIN COURSE ON SEC_COURSE_ID = COURSE_ID
  INNER JOIN DEPARTMENT ON CRS_DEPARTMENT = DEPARTMENT_ID
  INNER JOIN DEPT_CHAIR ON DEP_DEPT_CHAIR = DEPT_CHAIR_ID
  INNER JOIN STUDENT ON ENR_STUDENT_ID = STUDENT_ID
  INNER JOIN TERM ON ENR_TERM = TERM_ID
  LEFT JOIN (SELECT DISTINCT SFA_STUDENT_ID, SFA_AWARD_PERIOD
	FROM STUDENT_FA_TERM_AWARD
	WHERE SFA_AWARD LIKE ('%%BOG')
	OR SFA_AWARD = 'PELL') LOW_INCOME ON ENR_STUDENT_ID = SFA_STUDENT_ID
	AND ENR_TERM = SFA_AWARD_PERIOD
  WHERE DEPT_CHAIR_ID = '%s'
  AND TER_SORT between '%s' and '%s'
  AND (ENR_CENSUS_REG_FLAG = 'Y' OR ENR_CURRENT_REG_FLAG = 'Y')
  AND ENR_TERM LIKE '%%FA') LOWINCOME
GROUP BY ENR_TERM, DEPARTMENT, LOW_INCOME"
                  , program
                  , minTermSort
                  , maxTermSort
  )
  lowDf <- dbGetQuery(db, qLow)
  return(lowDf)
}

#get Low Income data from the database for TOTAL PROGRAM
progPercentLowTot <- function(program, minTermSort, maxTermSort) {
  
  qLow <- sprintf("SELECT ENR_TERM, PROGRAM, LOW_INCOME, COUNT(DISTINCT ENR_STUDENT_ID) HEADCOUNT
FROM (SELECT TER_SORT, ENR_TERM, 
  CASE 
	WHEN RIGHT(TER_SORT, 1) < '3' THEN LEFT(TER_SORT,4) - 1
	ELSE LEFT(TER_SORT, 4)
	END AS ACADEMIC_YEAR,
  DEC_DESC AS PROGRAM,
  DEP_DESC AS DEPARTMENT,
  ENR_STUDENT_ID,
  CASE 
	WHEN LOW_INCOME.SFA_STUDENT_ID IS NOT NULL THEN 'Y'
	ELSE 'N'
	END AS LOW_INCOME
  FROM ENROLLMENT
  INNER JOIN SECTION ON ENR_SECTION_ID = SECTION_ID
  INNER JOIN COURSE ON SEC_COURSE_ID = COURSE_ID
  INNER JOIN DEPARTMENT ON CRS_DEPARTMENT = DEPARTMENT_ID
  INNER JOIN DEPT_CHAIR ON DEP_DEPT_CHAIR = DEPT_CHAIR_ID
  INNER JOIN STUDENT ON ENR_STUDENT_ID = STUDENT_ID
  INNER JOIN TERM ON ENR_TERM = TERM_ID
  LEFT JOIN (SELECT DISTINCT SFA_STUDENT_ID, SFA_AWARD_PERIOD
	FROM STUDENT_FA_TERM_AWARD
	WHERE SFA_AWARD LIKE ('%%BOG')
	OR SFA_AWARD = 'PELL') LOW_INCOME ON ENR_STUDENT_ID = SFA_STUDENT_ID
	AND ENR_TERM = SFA_AWARD_PERIOD
  WHERE DEPT_CHAIR_ID = '%s'
  AND TER_SORT between '%s' and '%s'
  AND (ENR_CENSUS_REG_FLAG = 'Y' OR ENR_CURRENT_REG_FLAG = 'Y')
  AND ENR_TERM LIKE '%%FA') LOWINCOME
GROUP BY ENR_TERM, PROGRAM, LOW_INCOME"
                  , program
                  , minTermSort
                  , maxTermSort
  )
  lowDf <- dbGetQuery(db, qLow)
  return(lowDf)
}


#get Low Income data from the database for COLLEGE
percentLowCol <- function(minTermSort, maxTermSort) {
  
  qLow <- sprintf("SELECT ENR_TERM, LOW_INCOME, 'Butte College' PROGRAM, COUNT(DISTINCT ENR_STUDENT_ID) HEADCOUNT
FROM (SELECT TER_SORT, ENR_TERM, 
  ENR_STUDENT_ID,
  CASE 
	WHEN LOW_INCOME.SFA_STUDENT_ID IS NOT NULL THEN 'Y'
	ELSE 'N'
	END AS LOW_INCOME
  FROM ENROLLMENT
  INNER JOIN SECTION ON ENR_SECTION_ID = SECTION_ID
  INNER JOIN COURSE ON SEC_COURSE_ID = COURSE_ID
  INNER JOIN STUDENT ON ENR_STUDENT_ID = STUDENT_ID
  INNER JOIN TERM ON ENR_TERM = TERM_ID
  LEFT JOIN (SELECT DISTINCT SFA_STUDENT_ID, SFA_AWARD_PERIOD
	FROM STUDENT_FA_TERM_AWARD
	WHERE SFA_AWARD LIKE '%%BOG' 
	OR SFA_AWARD = 'PELL'
	) LOW_INCOME 
ON ENR_STUDENT_ID = SFA_STUDENT_ID
AND ENR_TERM = SFA_AWARD_PERIOD 
WHERE TER_SORT between '%s' and '%s'
AND (ENR_CENSUS_REG_FLAG = 'Y' OR ENR_CURRENT_REG_FLAG = 'Y')
AND ENR_TERM LIKE '%%FA') LOWINCOME
GROUP BY ENR_TERM, LOW_INCOME"
                  , minTermSort
                  , maxTermSort
  )
  lowDf <- dbGetQuery(db, qLow)
  return(lowDf)
}


#get DSPS data from the database for a PROGRAM
#Any student identified as DSPS at any time in history
progPercentDSPS <- function(program, minTermSort, maxTermSort) {
  
  qDSPS <- sprintf("SELECT STU_DISABILITY_FLAG, DEPARTMENT, COUNT(DISTINCT ENR_STUDENT_ID) HEADCOUNT
FROM (SELECT TER_SORT, ENR_TERM, 
  CASE 
	WHEN RIGHT(TER_SORT, 1) < '3' THEN LEFT(TER_SORT,4) - 1
	ELSE LEFT(TER_SORT, 4)
	END AS ACADEMIC_YEAR,
  DEC_DESC AS PROGRAM,
  DEP_DESC AS DEPARTMENT,
  STU_DISABILITY_FLAG,
  ENR_STUDENT_ID
  FROM ENROLLMENT
  INNER JOIN SECTION ON ENR_SECTION_ID = SECTION_ID
  INNER JOIN COURSE ON SEC_COURSE_ID = COURSE_ID
  INNER JOIN DEPARTMENT ON CRS_DEPARTMENT = DEPARTMENT_ID
  INNER JOIN DEPT_CHAIR ON DEP_DEPT_CHAIR = DEPT_CHAIR_ID
  INNER JOIN STUDENT ON ENR_STUDENT_ID = STUDENT_ID
  INNER JOIN TERM ON ENR_TERM = TERM_ID
  WHERE DEPT_CHAIR_ID = '%s'
  AND TER_SORT between '%s' and '%s'
  AND (ENR_CENSUS_REG_FLAG = 'Y' OR ENR_CURRENT_REG_FLAG = 'Y')) DSPS
GROUP BY DEPARTMENT, STU_DISABILITY_FLAG"
                   , program
                   , minTermSort
                   , maxTermSort
  )
  dspsDf <- dbGetQuery(db, qDSPS)
  return(dspsDf)
}

progPercentDSPSTot <- function(program, minTermSort, maxTermSort) {
  
  qDSPS <- sprintf("SELECT STU_DISABILITY_FLAG, PROGRAM, COUNT(DISTINCT ENR_STUDENT_ID) HEADCOUNT
FROM (SELECT TER_SORT, ENR_TERM, 
  CASE 
	WHEN RIGHT(TER_SORT, 1) < '3' THEN LEFT(TER_SORT,4) - 1
	ELSE LEFT(TER_SORT, 4)
	END AS ACADEMIC_YEAR,
  DEC_DESC AS PROGRAM,
  DEP_DESC AS DEPARTMENT,
  STU_DISABILITY_FLAG,
  ENR_STUDENT_ID
  FROM ENROLLMENT
  INNER JOIN SECTION ON ENR_SECTION_ID = SECTION_ID
  INNER JOIN COURSE ON SEC_COURSE_ID = COURSE_ID
  INNER JOIN DEPARTMENT ON CRS_DEPARTMENT = DEPARTMENT_ID
  INNER JOIN DEPT_CHAIR ON DEP_DEPT_CHAIR = DEPT_CHAIR_ID
  INNER JOIN STUDENT ON ENR_STUDENT_ID = STUDENT_ID
  INNER JOIN TERM ON ENR_TERM = TERM_ID
  WHERE DEPT_CHAIR_ID = '%s'
  AND TER_SORT between '%s' and '%s'
  AND (ENR_CENSUS_REG_FLAG = 'Y' OR ENR_CURRENT_REG_FLAG = 'Y')) DSPS
GROUP BY PROGRAM, STU_DISABILITY_FLAG"
                   , program
                   , minTermSort
                   , maxTermSort
  )
  dspsDf <- dbGetQuery(db, qDSPS)
  return(dspsDf)
}

#get DSPS data from the database for the College
#Any student identified as DSPS at any time in history
percentDSPSCol <- function(minTermSort, maxTermSort) {
  
  qDSPS <- sprintf("SELECT STU_DISABILITY_FLAG, COUNT(DISTINCT ENR_STUDENT_ID) HEADCOUNT
FROM (SELECT TER_SORT, ENR_TERM, 
  CASE 
	WHEN RIGHT(TER_SORT, 1) < '3' THEN LEFT(TER_SORT,4) - 1
	ELSE LEFT(TER_SORT, 4)
	END AS ACADEMIC_YEAR,
  STU_DISABILITY_FLAG,
  ENR_STUDENT_ID
  FROM ENROLLMENT
  INNER JOIN SECTION ON ENR_SECTION_ID = SECTION_ID
  INNER JOIN STUDENT ON ENR_STUDENT_ID = STUDENT_ID
  INNER JOIN TERM ON ENR_TERM = TERM_ID
  WHERE TER_SORT between '%s' and '%s'
  AND (ENR_CENSUS_REG_FLAG = 'Y' OR ENR_CURRENT_REG_FLAG = 'Y')) DSPS
GROUP BY STU_DISABILITY_FLAG"
                   , minTermSort
                   , maxTermSort
  )
  dspsDf <- dbGetQuery(db, qDSPS)
  return(dspsDf)
}

#get FOSTER data from the database for a PROGRAM
progPercentFoster <- function(program, minTermSort, maxTermSort) {
  
  qFoster <- sprintf("SELECT STU_FOSTER_YOUTH_FLAG, DEPARTMENT, COUNT(DISTINCT ENR_STUDENT_ID) HEADCOUNT
FROM (SELECT TER_SORT, ENR_TERM, 
  CASE 
	WHEN RIGHT(TER_SORT, 1) < '3' THEN LEFT(TER_SORT,4) - 1
	ELSE LEFT(TER_SORT, 4)
	END AS ACADEMIC_YEAR,
  DEC_DESC AS PROGRAM,
  DEP_DESC AS DEPARTMENT,
  STU_FOSTER_YOUTH_FLAG,
  ENR_STUDENT_ID
  FROM ENROLLMENT
  INNER JOIN SECTION ON ENR_SECTION_ID = SECTION_ID
  INNER JOIN COURSE ON SEC_COURSE_ID = COURSE_ID
  INNER JOIN DEPARTMENT ON CRS_DEPARTMENT = DEPARTMENT_ID
  INNER JOIN DEPT_CHAIR ON DEP_DEPT_CHAIR = DEPT_CHAIR_ID
  INNER JOIN STUDENT ON ENR_STUDENT_ID = STUDENT_ID
  INNER JOIN TERM ON ENR_TERM = TERM_ID
  WHERE DEPT_CHAIR_ID = '%s'
  AND TER_SORT between '%s' and '%s'
  AND (ENR_CENSUS_REG_FLAG = 'Y' OR ENR_CURRENT_REG_FLAG = 'Y')) DSPS
GROUP BY DEPARTMENT, STU_FOSTER_YOUTH_FLAG"
                     , program
                     , minTermSort
                     , maxTermSort
  )
  fosterDf <- dbGetQuery(db, qFoster)
  return(fosterDf)
}

progPercentFosterTot <- function(program, minTermSort, maxTermSort) {
  
  qFoster <- sprintf("SELECT STU_FOSTER_YOUTH_FLAG, PROGRAM, COUNT(DISTINCT ENR_STUDENT_ID) HEADCOUNT
FROM (SELECT TER_SORT, ENR_TERM, 
  CASE 
	WHEN RIGHT(TER_SORT, 1) < '3' THEN LEFT(TER_SORT,4) - 1
	ELSE LEFT(TER_SORT, 4)
	END AS ACADEMIC_YEAR,
  DEC_DESC AS PROGRAM,
  DEP_DESC AS DEPARTMENT,
  STU_FOSTER_YOUTH_FLAG,
  ENR_STUDENT_ID
  FROM ENROLLMENT
  INNER JOIN SECTION ON ENR_SECTION_ID = SECTION_ID
  INNER JOIN COURSE ON SEC_COURSE_ID = COURSE_ID
  INNER JOIN DEPARTMENT ON CRS_DEPARTMENT = DEPARTMENT_ID
  INNER JOIN DEPT_CHAIR ON DEP_DEPT_CHAIR = DEPT_CHAIR_ID
  INNER JOIN STUDENT ON ENR_STUDENT_ID = STUDENT_ID
  INNER JOIN TERM ON ENR_TERM = TERM_ID
  WHERE DEPT_CHAIR_ID = '%s'
  AND TER_SORT between '%s' and '%s'
  AND (ENR_CENSUS_REG_FLAG = 'Y' OR ENR_CURRENT_REG_FLAG = 'Y')) DSPS
GROUP BY PROGRAM, STU_FOSTER_YOUTH_FLAG"
                     , program
                     , minTermSort
                     , maxTermSort
  )
  fosterDf <- dbGetQuery(db, qFoster)
  return(fosterDf)
}


#get FOSTER data from the database for the College
percentFosterCol <- function(minTermSort, maxTermSort) {
  
  qFoster <- sprintf("SELECT STU_FOSTER_YOUTH_FLAG, COUNT(DISTINCT ENR_STUDENT_ID) HEADCOUNT
FROM (SELECT TER_SORT, ENR_TERM, 
  CASE 
	WHEN RIGHT(TER_SORT, 1) < '3' THEN LEFT(TER_SORT,4) - 1
	ELSE LEFT(TER_SORT, 4)
	END AS ACADEMIC_YEAR,
  STU_FOSTER_YOUTH_FLAG,
  ENR_STUDENT_ID
  FROM ENROLLMENT
  INNER JOIN SECTION ON ENR_SECTION_ID = SECTION_ID
  INNER JOIN STUDENT ON ENR_STUDENT_ID = STUDENT_ID
  INNER JOIN TERM ON ENR_TERM = TERM_ID
  WHERE TER_SORT between '%s' and '%s'
  AND (ENR_CENSUS_REG_FLAG = 'Y' OR ENR_CURRENT_REG_FLAG = 'Y')) DSPS
GROUP BY STU_FOSTER_YOUTH_FLAG"
                     , minTermSort
                     , maxTermSort
  )
  fosterDf <- dbGetQuery(db, qFoster)
  return(fosterDf)
}

#get VET data from the database for a PROGRAM
progPercentVet <- function(program, minTermSort, maxTermSort) {
  
  qVet <- sprintf("SELECT VETERAN_FLAG, DEPARTMENT, COUNT(DISTINCT ENR_STUDENT_ID) HEADCOUNT
FROM (SELECT TER_SORT, ENR_TERM, 
  CASE 
	WHEN RIGHT(TER_SORT, 1) < '3' THEN LEFT(TER_SORT,4) - 1
	ELSE LEFT(TER_SORT, 4)
	END AS ACADEMIC_YEAR,
  DEC_DESC AS PROGRAM,
  DEP_DESC AS DEPARTMENT,
  CASE
  WHEN STU_VERIFIED_VETERAN_FLAG <> 'N' THEN 'Y'
  ELSE 'N'
  END AS VETERAN_FLAG,
  ENR_STUDENT_ID
  FROM ENROLLMENT
  INNER JOIN SECTION ON ENR_SECTION_ID = SECTION_ID
  INNER JOIN COURSE ON SEC_COURSE_ID = COURSE_ID
  INNER JOIN DEPARTMENT ON CRS_DEPARTMENT = DEPARTMENT_ID
  INNER JOIN DEPT_CHAIR ON DEP_DEPT_CHAIR = DEPT_CHAIR_ID
  INNER JOIN STUDENT ON ENR_STUDENT_ID = STUDENT_ID
  INNER JOIN TERM ON ENR_TERM = TERM_ID
  WHERE DEPT_CHAIR_ID = '%s'
  AND TER_SORT between '%s' and '%s'
  AND (ENR_CENSUS_REG_FLAG = 'Y' OR ENR_CURRENT_REG_FLAG = 'Y')) VET
GROUP BY DEPARTMENT, VETERAN_FLAG"
                  , program
                  , minTermSort
                  , maxTermSort
  )
  vetDf <- dbGetQuery(db, qVet)
  return(vetDf)
}

progPercentVetTot <- function(program, minTermSort, maxTermSort) {
  
  qVet <- sprintf("SELECT VETERAN_FLAG, PROGRAM, COUNT(DISTINCT ENR_STUDENT_ID) HEADCOUNT
FROM (SELECT TER_SORT, ENR_TERM, 
  CASE 
	WHEN RIGHT(TER_SORT, 1) < '3' THEN LEFT(TER_SORT,4) - 1
	ELSE LEFT(TER_SORT, 4)
	END AS ACADEMIC_YEAR,
  DEC_DESC AS PROGRAM,
  DEP_DESC AS DEPARTMENT,
  CASE
  WHEN STU_VERIFIED_VETERAN_FLAG <> 'N' THEN 'Y'
  ELSE 'N'
  END AS VETERAN_FLAG,
  ENR_STUDENT_ID
  FROM ENROLLMENT
  INNER JOIN SECTION ON ENR_SECTION_ID = SECTION_ID
  INNER JOIN COURSE ON SEC_COURSE_ID = COURSE_ID
  INNER JOIN DEPARTMENT ON CRS_DEPARTMENT = DEPARTMENT_ID
  INNER JOIN DEPT_CHAIR ON DEP_DEPT_CHAIR = DEPT_CHAIR_ID
  INNER JOIN STUDENT ON ENR_STUDENT_ID = STUDENT_ID
  INNER JOIN TERM ON ENR_TERM = TERM_ID
  WHERE DEPT_CHAIR_ID = '%s'
  AND TER_SORT between '%s' and '%s'
  AND (ENR_CENSUS_REG_FLAG = 'Y' OR ENR_CURRENT_REG_FLAG = 'Y')) VET
GROUP BY PROGRAM, VETERAN_FLAG"
                  , program
                  , minTermSort
                  , maxTermSort
  )
  vetDf <- dbGetQuery(db, qVet)
  return(vetDf)
}

#get Vet data from the database for the College
percentVetCol <- function(minTermSort, maxTermSort) {
  
  qVet <- sprintf("SELECT VETERAN_FLAG, COUNT(DISTINCT ENR_STUDENT_ID) HEADCOUNT
FROM (SELECT TER_SORT, ENR_TERM, 
  CASE 
	WHEN RIGHT(TER_SORT, 1) < '3' THEN LEFT(TER_SORT,4) - 1
	ELSE LEFT(TER_SORT, 4)
	END AS ACADEMIC_YEAR,
  CASE
  WHEN STU_VERIFIED_VETERAN_FLAG <> 'N' THEN 'Y'
  ELSE 'N'
  END AS VETERAN_FLAG,
  ENR_STUDENT_ID
  FROM ENROLLMENT
  INNER JOIN SECTION ON ENR_SECTION_ID = SECTION_ID
  INNER JOIN COURSE ON SEC_COURSE_ID = COURSE_ID
  INNER JOIN STUDENT ON ENR_STUDENT_ID = STUDENT_ID
  INNER JOIN TERM ON ENR_TERM = TERM_ID
  WHERE TER_SORT between '%s' and '%s'
  AND (ENR_CENSUS_REG_FLAG = 'Y' OR ENR_CURRENT_REG_FLAG = 'Y')) VET
GROUP BY VETERAN_FLAG"
                  , minTermSort
                  , maxTermSort
  )
  vetDf <- dbGetQuery(db, qVet)
  return(vetDf)
}

####################### ENROLLMENTS ###########################################################

#get Enrollment data from the database for a PROGRAM
progEnrollment <- function(program, minTermSort, maxTermSort) {
  
  qEnrollment <- sprintf("SELECT ACADEMIC_YEAR, PROGRAM, DEPARTMENT, COUNT(ENR_STUDENT_ID) ENROLLMENT
  FROM(SELECT TER_SORT, ENR_TERM, 
  CASE 
	WHEN RIGHT(TER_SORT, 1) < '3' THEN LEFT(TER_SORT,4) - 1
	ELSE LEFT(TER_SORT, 4)
	END AS ACADEMIC_YEAR,
  DEC_DESC AS PROGRAM,
  DEP_DESC AS DEPARTMENT,
  ENR_STUDENT_ID
  FROM ENROLLMENT
  INNER JOIN SECTION ON ENR_SECTION_ID = SECTION_ID
  INNER JOIN COURSE ON SEC_COURSE_ID = COURSE_ID
  INNER JOIN DEPARTMENT ON CRS_DEPARTMENT = DEPARTMENT_ID
  INNER JOIN DEPT_CHAIR ON DEP_DEPT_CHAIR = DEPT_CHAIR_ID
  INNER JOIN STUDENT ON ENR_STUDENT_ID = STUDENT_ID
  INNER JOIN TERM ON ENR_TERM = TERM_ID
  WHERE DEPT_CHAIR_ID = '%s'
  AND TER_SORT between '%s' and '%s'
  AND (ENR_CENSUS_REG_FLAG = 'Y' OR ENR_CURRENT_REG_FLAG = 'Y')) STUDENTS
  GROUP BY ACADEMIC_YEAR, PROGRAM, DEPARTMENT"
                         , program
                         , minTermSort
                         , maxTermSort
  )
  Enrollment <- dbGetQuery(db, qEnrollment)
  return(Enrollment)
}

#get TERM Enrollment data from the database for a PROGRAM in Total
progEnrollmentTerm <- function(program, minTermSort, maxTermSort) {
  
  qEnrollment <- sprintf("SELECT RIGHT(ENR_TERM, 2) PERIOD, 
  CASE 
	WHEN RIGHT(TER_SORT, 1) < '3' THEN LEFT(TER_SORT,4) - 1
	ELSE LEFT(TER_SORT, 4)
	END AS ACADEMIC_YEAR,
  DEC_DESC AS PROGRAM,
  DEP_DESC AS DEPARTMENT,
  COUNT(ENR_STUDENT_ID) ENROLLMENT
  FROM ENROLLMENT
  INNER JOIN SECTION ON ENR_SECTION_ID = SECTION_ID
  INNER JOIN COURSE ON SEC_COURSE_ID = COURSE_ID
  INNER JOIN DEPARTMENT ON CRS_DEPARTMENT = DEPARTMENT_ID
  INNER JOIN DEPT_CHAIR ON DEP_DEPT_CHAIR = DEPT_CHAIR_ID
  INNER JOIN STUDENT ON ENR_STUDENT_ID = STUDENT_ID
  INNER JOIN TERM ON ENR_TERM = TERM_ID
  WHERE DEPT_CHAIR_ID = '%s'
  AND TER_SORT between '%s' and '%s'
  AND (ENR_CENSUS_REG_FLAG = 'Y' OR ENR_CURRENT_REG_FLAG = 'Y')
  GROUP BY TER_SORT, ENR_TERM, DEC_DESC, DEP_DESC"
                         , program
                         , minTermSort
                         , maxTermSort
  )
  Enrollment <- dbGetQuery(db, qEnrollment)
  return(Enrollment)
}

####################### Majors ###########################################################

#get Distinct Headcount data of students by declared major in the program
progMajorHC <- function(program, minTermSort, maxTermSort) {
  
  qDistinctMHC <- sprintf("SELECT ENR_TERM, DEC_DESC PROGRAM,  DEP_DESC DEPARTMENT, ACP_TITLE, ACP_DEG_CERT_TYPE, 
  COUNT(DISTINCT ENR_STUDENT_ID) HEADCOUNT
  FROM ENROLLMENT
  INNER JOIN STUDENT_TERM ON ENR_STUDENT_ID = STT_STUDENT_ID
  AND ENR_TERM = STT_TERM
  INNER JOIN ACADEMIC_PROGRAM ON STT_ACADEMIC_PROGRAM = ACADEMIC_PROGRAM_ID
  INNER JOIN SECTION ON ENR_SECTION_ID = SECTION_ID
  INNER JOIN COURSE ON SEC_COURSE_ID = COURSE_ID
  INNER JOIN DEPARTMENT ON ACP_DEPARTMENT = DEPARTMENT_ID
  INNER JOIN DEPT_CHAIR ON DEP_DEPT_CHAIR = DEPT_CHAIR_ID
  INNER JOIN STUDENT ON ENR_STUDENT_ID = STUDENT_ID
  INNER JOIN TERM ON ENR_TERM = TERM_ID
  WHERE DEPT_CHAIR_ID = '%s'
  AND TER_SORT = (SELECT MAX(TER_SORT)
	FROM TERM
	WHERE TER_SORT between '%s' and '%s'
	AND TERM_ID LIKE '%%FA')
  AND (ENR_CENSUS_REG_FLAG = 'Y' OR ENR_CURRENT_REG_FLAG = 'Y')
  GROUP BY ENR_TERM, DEC_DESC, DEP_DESC, ACP_TITLE, ACP_DEG_CERT_TYPE"
                         , program
                         , minTermSort
                         , maxTermSort
  )
  DistinctMHC <- dbGetQuery(db, qDistinctMHC)
  return(DistinctMHC)
}

#get Distinct Headcount data of students by declared major - students taking classes in the program
majorHC <- function(program, minTermSort, maxTermSort) {
  
  qMajorHC <- sprintf("SELECT ACADEMIC_YEAR, PROGRAM, DEPARTMENT, MAJOR_DEPARTMENT, ACP_DEG_CERT_TYPE, 
  COUNT(DISTINCT ENR_STUDENT_ID) HEADCOUNT
  FROM(SELECT TER_SORT, ENR_TERM, 
  CASE 
	WHEN RIGHT(TER_SORT, 1) < '3' THEN LEFT(TER_SORT,4) - 1
	ELSE LEFT(TER_SORT, 4)
	END AS ACADEMIC_YEAR,
  DEC_DESC AS PROGRAM,
  DEP1.DEP_DESC AS DEPARTMENT,
  DEP2.DEP_DESC AS MAJOR_DEPARTMENT,
  ACP_TITLE,
  ACP_DEG_CERT_TYPE,
  ENR_STUDENT_ID
  FROM ENROLLMENT
  INNER JOIN STUDENT_TERM ON ENR_STUDENT_ID = STT_STUDENT_ID
  AND ENR_TERM = STT_TERM
  INNER JOIN ACADEMIC_PROGRAM ON STT_ACADEMIC_PROGRAM = ACADEMIC_PROGRAM_ID
  INNER JOIN DEPARTMENT DEP2 ON ACADEMIC_PROGRAM.ACP_DEPARTMENT = DEP2.DEPARTMENT_ID 
  INNER JOIN SECTION ON ENR_SECTION_ID = SECTION_ID
  INNER JOIN COURSE ON SEC_COURSE_ID = COURSE_ID
  INNER JOIN DEPARTMENT DEP1 ON CRS_DEPARTMENT = DEP1.DEPARTMENT_ID
  INNER JOIN DEPT_CHAIR ON DEP1.DEP_DEPT_CHAIR = DEPT_CHAIR_ID
  INNER JOIN STUDENT ON ENR_STUDENT_ID = STUDENT_ID
  INNER JOIN TERM ON ENR_TERM = TERM_ID
  WHERE DEPT_CHAIR_ID = '%s'
  AND TER_SORT between '%s' and '%s'
  AND (ENR_CENSUS_REG_FLAG = 'Y' OR ENR_CURRENT_REG_FLAG = 'Y')) STUDENTS
  GROUP BY ACADEMIC_YEAR, PROGRAM, MAJOR_DEPARTMENT, ACP_DEG_CERT_TYPE, DEPARTMENT"
                          , program
                          , minTermSort
                          , maxTermSort
  )
  MajorHC <- dbGetQuery(db, qMajorHC)
  return(MajorHC)
}

#get Distinct Headcount data of students who earned a degree in the program AND THE MAJOR THEY ORIGINALLY HAD
progMajorIn <- function(program, minTermSort, maxTermSort) {
  
  qprogMajorIn <- sprintf("SELECT SDC_TERM,
FIRST_MAJORS.DEC_DESC FIRST_PROGRAM,
FIRST_MAJORS.DEP_DESC FIRST_DEPARTMENT, 
DEG_CHAIR.DEC_DESC END_PROGRAM, 
DEG_DEPARTMENT.DEP_DESC END_DEPARTMENT, 
ACP_TITLE END_AWARD, 
ACP_DEG_CERT_TYPE ENR_AWARD_TYPE, 
COUNT(STP_STUDENT_ID) HEADCOUNT
FROM 
-- FINDS THE FIRST PRIMARY MAJOR - PRECIDENT GIVEN TO DEGREE, THEN CERT, THEN UNDECLARED
(SELECT DISTINCT SP.STP_STUDENT_ID, SORTED_MAJORS.ACADEMIC_PROGRAM_ID, SORTED_MAJORS.DEC_DESC, SORTED_MAJORS.DEP_DESC, SORTED_MAJORS.DEPT_CHAIR_ID
FROM STUDENT_PROGRAM SP
CROSS APPLY 
	(SELECT TOP 1 ACADEMIC_PROGRAM_ID, ACP_TITLE, ACP_DEG_CERT_TYPE, ACP_DEPARTMENT, DEC_DESC, DEP_DESC, DEPT_CHAIR_ID,
	CASE
		WHEN ACP_DEG_CERT_TYPE LIKE 'A%%' THEN '1'
		WHEN ACP_DEG_CERT_TYPE LIKE 'C%%' THEN '2'
		WHEN ACP_DEG_CERT_TYPE IS NULL THEN '3'
	END MAJOR_SORT
	FROM STUDENT_PROGRAM
	INNER JOIN ACADEMIC_PROGRAM ON STP_ACADEMIC_PROGRAM = ACADEMIC_PROGRAM_ID
	LEFT JOIN DEPARTMENT FM_DEPARTMENT ON ACP_DEPARTMENT = DEPARTMENT_ID
	LEFT JOIN DEPT_CHAIR FM_CHAIR ON DEP_DEPT_CHAIR = DEPT_CHAIR_ID
	WHERE STP_STUDENT_ID = SP.STP_STUDENT_ID
	ORDER BY MAJOR_SORT) SORTED_MAJORS
) FIRST_MAJORS
INNER JOIN STUDENT_DEG_CERT ON STP_STUDENT_ID = SDC_STUDENT_ID  -- AWARDS EARNED BY STUDENTS
INNER JOIN ACADEMIC_PROGRAM ON SDC_ACADEMIC_PROGRAM = ACADEMIC_PROGRAM.ACADEMIC_PROGRAM_ID -- LINK AWARD INFO TO AWARDS EARNED BY STUDENTS
LEFT JOIN DEPARTMENT DEG_DEPARTMENT ON ACP_DEPARTMENT = DEG_DEPARTMENT.DEPARTMENT_ID  -- LINK DEPARTMENT ON EARNED AWARDS 
LEFT JOIN DEPT_CHAIR DEG_CHAIR ON DEP_DEPT_CHAIR = DEG_CHAIR.DEPT_CHAIR_ID -- LINK CHAIR ON EARNED AWARDS
INNER JOIN TERM ON SDC_TERM = TERM_ID  -- WE ONLY WANT THE LATEST SPRING TERM
WHERE DEG_CHAIR.DEPT_CHAIR_ID = '%s'
AND TER_SORT between '%s' and '%s'
--AND TERM_ID LIKE '%%SP'
GROUP BY SDC_TERM,
FIRST_MAJORS.DEC_DESC,
FIRST_MAJORS.DEP_DESC, 
DEG_CHAIR.DEC_DESC, 
DEG_DEPARTMENT.DEP_DESC, 
ACP_TITLE, 
ACP_DEG_CERT_TYPE
"
                          , program
                          , minTermSort
                          , maxTermSort
  )
  ProgMajorIn <- dbGetQuery(db, qprogMajorIn)
  return(ProgMajorIn)
}

#get Distinct Headcount data of students who had a major in the program and earned a degree in something else
progMajorOut <- function(program, minTermSort, maxTermSort) {
  
  qprogMajorOut <- sprintf("
SELECT SDC_TERM,
FIRST_MAJORS.DEC_DESC FIRST_PROGRAM,
FIRST_MAJORS.DEP_DESC FIRST_DEPARTMENT, 
DEG_CHAIR.DEC_DESC END_PROGRAM, 
DEG_DEPARTMENT.DEP_DESC END_DEPARTMENT, 
ACP_TITLE END_AWARD, 
ACP_DEG_CERT_TYPE ENR_AWARD_TYPE, 
COUNT(STP_STUDENT_ID) HEADCOUNT
FROM 
-- FINDS THE FIRST PRIMARY MAJOR - PRECIDENT GIVEN TO DEGREE, THEN CERT, THEN UNDECLARED
(SELECT DISTINCT SP.STP_STUDENT_ID, SORTED_MAJORS.ACADEMIC_PROGRAM_ID, SORTED_MAJORS.DEC_DESC, SORTED_MAJORS.DEP_DESC, SORTED_MAJORS.DEPT_CHAIR_ID
FROM STUDENT_PROGRAM SP
CROSS APPLY 
	(SELECT TOP 1 ACADEMIC_PROGRAM_ID, ACP_TITLE, ACP_DEG_CERT_TYPE, ACP_DEPARTMENT, DEC_DESC, DEP_DESC, DEPT_CHAIR_ID,
	CASE
		WHEN ACP_DEG_CERT_TYPE LIKE 'A%%' THEN '1'
		WHEN ACP_DEG_CERT_TYPE LIKE 'C%%' THEN '2'
		WHEN ACP_DEG_CERT_TYPE IS NULL THEN '3'
	END MAJOR_SORT
	FROM STUDENT_PROGRAM
	INNER JOIN ACADEMIC_PROGRAM ON STP_ACADEMIC_PROGRAM = ACADEMIC_PROGRAM_ID
	LEFT JOIN DEPARTMENT FM_DEPARTMENT ON ACP_DEPARTMENT = DEPARTMENT_ID
	LEFT JOIN DEPT_CHAIR FM_CHAIR ON DEP_DEPT_CHAIR = DEPT_CHAIR_ID
	WHERE STP_STUDENT_ID = SP.STP_STUDENT_ID
	ORDER BY MAJOR_SORT) SORTED_MAJORS
) FIRST_MAJORS
INNER JOIN STUDENT_DEG_CERT ON STP_STUDENT_ID = SDC_STUDENT_ID  -- AWARDS EARNED BY STUDENTS
INNER JOIN ACADEMIC_PROGRAM ON SDC_ACADEMIC_PROGRAM = ACADEMIC_PROGRAM.ACADEMIC_PROGRAM_ID -- LINK AWARD INFO TO AWARDS EARNED BY STUDENTS
LEFT JOIN DEPARTMENT DEG_DEPARTMENT ON ACP_DEPARTMENT = DEG_DEPARTMENT.DEPARTMENT_ID  -- LINK DEPARTMENT ON EARNED AWARDS 
LEFT JOIN DEPT_CHAIR DEG_CHAIR ON DEP_DEPT_CHAIR = DEG_CHAIR.DEPT_CHAIR_ID -- LINK CHAIR ON EARNED AWARDS
INNER JOIN TERM ON SDC_TERM = TERM_ID  -- WE ONLY WANT THE LATEST SPRING TERM
WHERE DEG_CHAIR.DEPT_CHAIR_ID <> '%s'
AND FIRST_MAJORS.DEPT_CHAIR_ID = '%s'
AND TER_SORT between '%s' and '%s'
--AND TERM_ID LIKE '%%SP'
GROUP BY SDC_TERM,
FIRST_MAJORS.DEC_DESC,
FIRST_MAJORS.DEP_DESC, 
DEG_CHAIR.DEC_DESC, 
DEG_DEPARTMENT.DEP_DESC, 
ACP_TITLE, 
ACP_DEG_CERT_TYPE
"

                          , program
                          , program
                          , minTermSort
                          , maxTermSort
  )
  ProgMajorOut <- dbGetQuery(db, qprogMajorOut)
  return(ProgMajorOut)
}


#get Distinct Headcount data of students who earned a degree in the program AND THE MAJOR THEY ORIGINALLY HAD FOR THE INSTITUTION
progMajorInCol <- function( minTermSort, maxTermSort) {
  
  qprogMajorIn <- sprintf("SELECT SDC_TERM,
FIRST_MAJORS.DEC_DESC FIRST_PROGRAM,
FIRST_MAJORS.DEP_DESC FIRST_DEPARTMENT, 
DEG_CHAIR.DEC_DESC END_PROGRAM, 
DEG_DEPARTMENT.DEP_DESC END_DEPARTMENT, 
ACP_TITLE END_AWARD, 
ACP_DEG_CERT_TYPE ENR_AWARD_TYPE, 
COUNT(STP_STUDENT_ID) HEADCOUNT
FROM 
-- FINDS THE FIRST PRIMARY MAJOR - PRECIDENT GIVEN TO DEGREE, THEN CERT, THEN UNDECLARED
(SELECT DISTINCT SP.STP_STUDENT_ID, SORTED_MAJORS.ACADEMIC_PROGRAM_ID, SORTED_MAJORS.DEC_DESC, SORTED_MAJORS.DEP_DESC, SORTED_MAJORS.DEPT_CHAIR_ID
FROM STUDENT_PROGRAM SP
CROSS APPLY 
	(SELECT TOP 1 ACADEMIC_PROGRAM_ID, ACP_TITLE, ACP_DEG_CERT_TYPE, ACP_DEPARTMENT, DEC_DESC, DEP_DESC, DEPT_CHAIR_ID,
	CASE
		WHEN ACP_DEG_CERT_TYPE LIKE 'A%%' THEN '1'
		WHEN ACP_DEG_CERT_TYPE LIKE 'C%%' THEN '2'
		WHEN ACP_DEG_CERT_TYPE IS NULL THEN '3'
	END MAJOR_SORT
	FROM STUDENT_PROGRAM
	INNER JOIN ACADEMIC_PROGRAM ON STP_ACADEMIC_PROGRAM = ACADEMIC_PROGRAM_ID
	LEFT JOIN DEPARTMENT FM_DEPARTMENT ON ACP_DEPARTMENT = DEPARTMENT_ID
	LEFT JOIN DEPT_CHAIR FM_CHAIR ON DEP_DEPT_CHAIR = DEPT_CHAIR_ID
	WHERE STP_STUDENT_ID = SP.STP_STUDENT_ID
	ORDER BY MAJOR_SORT) SORTED_MAJORS
) FIRST_MAJORS
INNER JOIN STUDENT_DEG_CERT ON STP_STUDENT_ID = SDC_STUDENT_ID  -- AWARDS EARNED BY STUDENTS
INNER JOIN ACADEMIC_PROGRAM ON SDC_ACADEMIC_PROGRAM = ACADEMIC_PROGRAM.ACADEMIC_PROGRAM_ID -- LINK AWARD INFO TO AWARDS EARNED BY STUDENTS
LEFT JOIN DEPARTMENT DEG_DEPARTMENT ON ACP_DEPARTMENT = DEG_DEPARTMENT.DEPARTMENT_ID  -- LINK DEPARTMENT ON EARNED AWARDS 
LEFT JOIN DEPT_CHAIR DEG_CHAIR ON DEP_DEPT_CHAIR = DEG_CHAIR.DEPT_CHAIR_ID -- LINK CHAIR ON EARNED AWARDS
INNER JOIN TERM ON SDC_TERM = TERM_ID  -- WE ONLY WANT THE LATEST SPRING TERM
WHERE TER_SORT between '%s' and '%s'
--AND TERM_ID LIKE '%%SP'
GROUP BY SDC_TERM,
FIRST_MAJORS.DEC_DESC,
FIRST_MAJORS.DEP_DESC, 
DEG_CHAIR.DEC_DESC, 
DEG_DEPARTMENT.DEP_DESC, 
ACP_TITLE, 
ACP_DEG_CERT_TYPE
"
                          , minTermSort
                          , maxTermSort
  )
  ProgMajorIn <- dbGetQuery(db, qprogMajorIn)
  return(ProgMajorIn)
}

######################## CAPACITY FTES and Efficiency#######################################################################
#FOR COURSES IN THE PROGRAM
progCapacity <- function(program, minTermSort, maxTermSort) {
  
  qprogCapacity <- sprintf("SELECT DEP_DESC 'Dept', ACADEMIC_YEAR 'Year', SEC_SUBJECT + '-' + SEC_COURSE_NO 'Crse',
  SEC_SHORT_TITLE 'Title', LOC_DESC 'Loc', SEC_MODE 'Mode', COUNT(SECTION_ID) 'Sec', SUM(SEC_CENSUS_ENRL) 
  'Enrl', CAST(SUM(SEC_FILL_RATE_NUMERATOR) / NULLIF(SUM(SEC_FILL_RATE_DENOMINATOR), 0) AS DECIMAL (18,2)) 'FR',
  CAST(SUM(SEC_TOTAL_FTES) AS DECIMAL (18,2)) FTES, CAST(SUM(SEC_FTEF) AS DECIMAL (18,2)) FTEF, CAST(SUM(SEC_TOTAL_FTES) /        NULLIF(SUM(SEC_FTEF), 0)AS DECIMAL (18,2)) Effcy
  FROM (SELECT DEP_DESC, 
    CASE 
	    WHEN RIGHT(TER_SORT, 1) < '3' THEN LEFT(TER_SORT,4) - 1
	    ELSE LEFT(TER_SORT, 4)
    END AS ACADEMIC_YEAR,
    SEC_SUBJECT, SEC_COURSE_NO, SEC_SHORT_TITLE, LOC_DESC, SEC_MODE, SECTION_ID, 
    SEC_CENSUS_ENRL, SEC_FILL_RATE_NUMERATOR, SEC_FILL_RATE_DENOMINATOR,
    SEC_TOTAL_FTES, SEC_FTEF
    FROM SECTION
     INNER JOIN DEPARTMENT ON SEC_DEPARTMENT = DEPARTMENT_ID
    INNER JOIN DEPT_CHAIR ON DEP_DEPT_CHAIR = DEPT_CHAIR_ID
    INNER JOIN LOCATION ON SEC_LOCATION = LOCATION_ID 
    INNER JOIN TERM ON SEC_TERM = TERM_ID
    WHERE SEC_ACTIVE_FLAG = 'Y'
    AND DEPT_CHAIR_ID = '%s'
    AND TER_SORT between '%s' and '%s') CAPACITY
  GROUP BY DEP_DESC, ACADEMIC_YEAR, SEC_SUBJECT, SEC_COURSE_NO, SEC_SHORT_TITLE, 
  LOC_DESC, SEC_MODE"
                          , program
                          , minTermSort
                          , maxTermSort
  )
  progCapacity <- dbGetQuery(db, qprogCapacity)
  return(progCapacity)
}

#CAPACITY FOR THE ENTIRE PROGRAM
progCapacityTOT <- function(program, minTermSort, maxTermSort) {
  
  qprogCapacityTOT <- sprintf("SELECT  ACADEMIC_YEAR 'Year', LOC_DESC 'Loc', 
  SEC_MODE 'Mode', COUNT(SECTION_ID) 'Sec', SUM(SEC_CENSUS_ENRL) 
  'Enrl', CAST(SUM(SEC_FILL_RATE_NUMERATOR) / NULLIF(SUM(SEC_FILL_RATE_DENOMINATOR), 0) AS DECIMAL (18,2)) 'FR',
  CAST(SUM(SEC_TOTAL_FTES) AS DECIMAL (18,2)) FTES, CAST(SUM(SEC_FTEF) AS DECIMAL(18,2)) FTEF, CAST(SUM(SEC_TOTAL_FTES) / NULLIF   (SUM(SEC_FTEF), 0) AS DECIMAL (18,2)) Effcy
  FROM (SELECT DEP_DESC, 
    CASE 
	    WHEN RIGHT(TER_SORT, 1) < '3' THEN LEFT(TER_SORT,4) - 1
	    ELSE LEFT(TER_SORT, 4)
    END AS ACADEMIC_YEAR,
    SEC_SUBJECT, SEC_COURSE_NO, SEC_SHORT_TITLE, LOC_DESC, SEC_MODE, SECTION_ID, 
    SEC_CENSUS_ENRL, SEC_FILL_RATE_NUMERATOR, SEC_FILL_RATE_DENOMINATOR,
    SEC_TOTAL_FTES, SEC_FTEF
    FROM SECTION
    INNER JOIN DEPARTMENT ON SEC_DEPARTMENT = DEPARTMENT_ID
    INNER JOIN DEPT_CHAIR ON DEP_DEPT_CHAIR = DEPT_CHAIR_ID
    INNER JOIN LOCATION ON SEC_LOCATION = LOCATION_ID 
    INNER JOIN TERM ON SEC_TERM = TERM_ID
    WHERE SEC_ACTIVE_FLAG = 'Y'
    AND DEPT_CHAIR_ID = '%s'
    AND TER_SORT between '%s' and '%s') CAPACITY
  GROUP BY ACADEMIC_YEAR, LOC_DESC, SEC_MODE"
                           , program
                           , minTermSort
                           , maxTermSort
  )
  ProgCapacity <- dbGetQuery(db, qprogCapacityTOT)
  return(ProgCapacity)
}

# FIND PROGRAM LOCATIONS and Modes
progLocations <- function(program, minTermSort, maxTermSort) {
  
  qprogCapacity <- sprintf("SELECT DISTINCT LOCATION_ID, SEC_MODE 
    FROM SECTION
     INNER JOIN DEPARTMENT ON SEC_DEPARTMENT = DEPARTMENT_ID
    INNER JOIN DEPT_CHAIR ON DEP_DEPT_CHAIR = DEPT_CHAIR_ID
    INNER JOIN LOCATION ON SEC_LOCATION = LOCATION_ID 
    INNER JOIN TERM ON SEC_TERM = TERM_ID
    WHERE SEC_ACTIVE_FLAG = 'Y'
    AND DEPT_CHAIR_ID = '%s'
    AND TER_SORT between '%s' and '%s'"
                           , program
                           , minTermSort
                           , maxTermSort
  )
  progCapacity <- dbGetQuery(db, qprogCapacity)
  return(progCapacity)
}

#CAPACITY FOR THE COLLEGE (ONLY THOSE LOCATIONS AND MODES THAT THE PROGRAM SERVES)
collegeCapacity <- function(location, modes, minTermSort, maxTermSort) {
  qcollegeCapacity <- sprintf("SELECT 'Butte College' 'Dept', ACADEMIC_YEAR 'Year', LOC_DESC 'Loc', 
  SEC_MODE 'Mode', COUNT(SECTION_ID) 'Sec', SUM(SEC_CENSUS_ENRL) 
  'Enrl', CAST(SUM(SEC_FILL_RATE_NUMERATOR) / NULLIF(SUM(SEC_FILL_RATE_DENOMINATOR), 0) AS DECIMAL(18,2)) 'FR',
  CAST(SUM(SEC_TOTAL_FTES) AS DECIMAL(18,2)) FTES, CAST(SUM(SEC_FTEF) AS DECIMAL(18,2)) FTEF, CAST(SUM(SEC_TOTAL_FTES) / NULLIF   (SUM(SEC_FTEF), 0) AS DECIMAL (18,2)) Effcy
  FROM (SELECT 
    CASE 
	    WHEN RIGHT(TER_SORT, 1) < '3' THEN LEFT(TER_SORT,4) - 1
	    ELSE LEFT(TER_SORT, 4)
    END AS ACADEMIC_YEAR,
    LOC_DESC, SEC_MODE, SECTION_ID, SEC_CENSUS_ENRL, SEC_FILL_RATE_NUMERATOR, SEC_FILL_RATE_DENOMINATOR,
    SEC_TOTAL_FTES, SEC_FTEF
    FROM SECTION
    INNER JOIN LOCATION ON SEC_LOCATION = LOCATION_ID 
    INNER JOIN TERM ON SEC_TERM = TERM_ID
    WHERE SEC_ACTIVE_FLAG = 'Y'
    AND LOCATION_ID %s
    AND SEC_MODE %s
    AND TER_SORT between '%s' and '%s') CAPACITY
  GROUP BY ACADEMIC_YEAR, LOC_DESC, SEC_MODE"
                          , location
                          , modes
                          , minTermSort
                          , maxTermSort
  )
  CollegeCapacity <- dbGetQuery(db, qcollegeCapacity)
  return(CollegeCapacity)
}

######################## Instructor Demographics ##########################################################################

# TOTAL Program Faculty Load and Percent by Contract Type  -- Most recent year

progPercentFacLoadTot <- function(program, progRecentYear, maxTermSort) {
  
  qLoadFac <- sprintf("SELECT ACADEMIC_YEAR, PROGRAM, FACULTY_TYPE, COUNT(DISTINCT FACULTY_ID) FACULTY_HEADCOUNT, CAST(SUM(SEF_LOAD)/100 AS DECIMAL(18,2)) FACULTY_LOAD
	FROM (SELECT
	 CASE 
		WHEN RIGHT(TER_SORT, 1) < '3' THEN LEFT(TER_SORT,4) - 1
		ELSE LEFT(TER_SORT, 4)
		END AS ACADEMIC_YEAR,
		DEC_DESC AS PROGRAM,
		FACULTY_ID,
		CASE
			WHEN SEF_TEACHING_ARRANGEMENT IN ('FN','WN','XN', 'FI') THEN 'Associate'
			WHEN SEF_TEACHING_ARRANGEMENT IN ('FR', 'FL', 'FO','FV','WR','XR') THEN 'Full-Time'
			ELSE 'Other'
		END AS FACULTY_TYPE,
		SEF_LOAD
	FROM 
	FACULTY 
	INNER JOIN SECTION_FACULTY ON FACULTY_ID = SEF_FACULTY_ID
	INNER JOIN SECTION ON SEF_SECTION_ID = SECTION_ID
	INNER JOIN TERM ON SEC_TERM = TERM_ID
	INNER JOIN COURSE ON SEC_COURSE_ID = COURSE_ID
	INNER JOIN DEPARTMENT ON CRS_DEPARTMENT = DEPARTMENT_ID
	INNER JOIN DEPT_CHAIR ON DEP_DEPT_CHAIR = DEPT_CHAIR_ID
	WHERE DEPT_CHAIR_ID = '%s'
	AND TER_SORT between '%s' and '%s'
	) INSTRUCTOR_GENDER
GROUP BY ACADEMIC_YEAR, PROGRAM, FACULTY_TYPE"
                        , program
                        , progRecentYear
                        , maxTermSort
  )
  loadDf <- dbGetQuery(db, qLoadFac)
  return(loadDf)
}

# College Total Faculty Gender  -- Most recent year
percentFacLoadCol <- function(progRecentYear, maxTermSort) {
  
  qLoadFac <- sprintf("SELECT ACADEMIC_YEAR, 'Butte College' PROGRAM, FACULTY_TYPE, COUNT(DISTINCT FACULTY_ID) FACULTY_HEADCOUNT, CAST(SUM(SEF_LOAD)/100 AS DECIMAL(18,2)) FACULTY_LOAD
	FROM (SELECT
	 CASE 
		WHEN RIGHT(TER_SORT, 1) < '3' THEN LEFT(TER_SORT,4) - 1
		ELSE LEFT(TER_SORT, 4)
		END AS ACADEMIC_YEAR,
		FACULTY_ID,
		CASE
			WHEN SEF_TEACHING_ARRANGEMENT IN ('FN','WN','XN', 'FI') THEN 'Associate'
			WHEN SEF_TEACHING_ARRANGEMENT IN ('FR', 'FL', 'FO','FV','WR','XR') THEN 'Full-Time'
			ELSE 'Other'
		END AS FACULTY_TYPE,
		SEF_LOAD
	FROM 
  FACULTY
	INNER JOIN SECTION_FACULTY ON FACULTY_ID = SEF_FACULTY_ID
	INNER JOIN SECTION ON SEF_SECTION_ID = SECTION_ID
	INNER JOIN TERM ON SEC_TERM = TERM_ID
	INNER JOIN COURSE ON SEC_COURSE_ID = COURSE_ID
	WHERE TER_SORT between '%s' and '%s'
	) INSTRUCTOR_GENDER
GROUP BY ACADEMIC_YEAR, FACULTY_TYPE"
                        , progRecentYear
                        , maxTermSort
  )
  loadDf <- dbGetQuery(db, qLoadFac)
  return(loadDf)
}


# TOTAL Program Faculty Ethnicity  -- Most recent year
progPercentFacEthnicityTot <- function(program, progRecentYear, maxTermSort) {
  
  qEthnicityFac <- sprintf("SELECT ACADEMIC_YEAR, PROGRAM, ETI_DESC, FACULTY_TYPE, COUNT(DISTINCT FACULTY_ID) FACULTY_HEADCOUNT,   SUM(SEF_LOAD)/100 FACULTY_LOAD
	FROM (SELECT
	 CASE 
		WHEN RIGHT(TER_SORT, 1) < '3' THEN LEFT(TER_SORT,4) - 1
		ELSE LEFT(TER_SORT, 4)
		END AS ACADEMIC_YEAR,
		DEC_DESC AS PROGRAM,
		ETI_DESC,
		FACULTY_ID,
		CASE
			WHEN SEF_TEACHING_ARRANGEMENT IN ('FN','WN','XN', 'FI') THEN 'Associate'
			WHEN SEF_TEACHING_ARRANGEMENT IN ('FR', 'FL', 'FO','FV','WR','XR') THEN 'Full-Time'
			ELSE 'Other'
		END AS FACULTY_TYPE,
		SEF_LOAD
	FROM 
		--FIND INSTRUCTOR'S RACE
		(SELECT GROUPED_RACES.ID,
		CASE 
			WHEN RACES IS NULL THEN 'X'
			WHEN LEFT(RACES, 1) = LEFT(RACES, 3) THEN 'T'
			WHEN LEN(RACES) = '2' THEN LEFT(RACES, 1)
			ELSE 'T'	
		END RACE
		FROM
			(SELECT ID, 
				STUFF((SELECT DISTINCT ',' + CAST(PER_RACES AS VARCHAR(30))
				FROM colleague_staging.dbo.PERSON_LS PERSON2
				WHERE PERSON2.ID = PERSON1.ID
				FOR XML PATH('')),1,1,'') AS RACES
			FROM colleague_staging.dbo.PERSON_LS PERSON1
			GROUP BY ID) GROUPED_RACES
		--REMOVE HISPANIC
		LEFT JOIN 
			(SELECT DISTINCT PERSON_LS.ID, 'H' HISPANIC
			FROM colleague_staging.dbo.PERSON_LS
			WHERE PER_ETHNICS = 'HIS'
			OR PER_RACES LIKE 'H%%') HISPANIC
		ON GROUPED_RACES.ID = HISPANIC.ID
		WHERE HISPANIC IS NULL
		--PULL HISPANIC BACK IN
		UNION ALL
		SELECT DISTINCT PERSON_LS.ID, 'H' HISPANIC
		FROM colleague_staging.dbo.PERSON_LS
		WHERE PER_ETHNICS = 'HIS'
		OR PER_RACES LIKE 'H%%') RACE_ETH
	RIGHT JOIN FACULTY ON RACE_ETH.ID = FACULTY_ID
	RIGHT JOIN SECTION_FACULTY ON FACULTY_ID = SEF_FACULTY_ID
	LEFT JOIN ETHNICITY_IPEDS ON RACE = ETHNICITY_IPEDS_ID
	INNER JOIN SECTION ON SEF_SECTION_ID = SECTION_ID
	INNER JOIN TERM ON SEC_TERM = TERM_ID
	INNER JOIN COURSE ON SEC_COURSE_ID = COURSE_ID
	INNER JOIN DEPARTMENT ON CRS_DEPARTMENT = DEPARTMENT_ID
	INNER JOIN DEPT_CHAIR ON DEP_DEPT_CHAIR = DEPT_CHAIR_ID
	WHERE DEPT_CHAIR_ID = '%s'
	AND TER_SORT between '%s' and '%s'
	) INSTRUCTOR_ETH
GROUP BY ACADEMIC_YEAR, PROGRAM, ETI_DESC, FACULTY_TYPE"
                           , program
                           , progRecentYear
                           , maxTermSort
  )
  ethDf <- dbGetQuery(db, qEthnicityFac)
  return(ethDf)
}

# College Total Faculty Ethnicity  -- Most recent year
percentFacEthnicityCol <- function(progRecentYear, maxTermSort) {
  
  qEthnicityFac <- sprintf("SELECT ACADEMIC_YEAR, 'Butte College' PROGRAM, ETI_DESC, FACULTY_TYPE, COUNT(DISTINCT FACULTY_ID)      FACULTY_HEADCOUNT, SUM(SEF_LOAD)/100 FACULTY_LOAD
	FROM (SELECT
	 CASE 
		WHEN RIGHT(TER_SORT, 1) < '3' THEN LEFT(TER_SORT,4) - 1
		ELSE LEFT(TER_SORT, 4)
		END AS ACADEMIC_YEAR,
		ETI_DESC,
		FACULTY_ID,
		CASE
			WHEN SEF_TEACHING_ARRANGEMENT IN ('FN','WN','XN', 'FI') THEN 'Associate'
			WHEN SEF_TEACHING_ARRANGEMENT IN ('FR', 'FL', 'FO','FV','WR','XR') THEN 'Full-Time'
			ELSE 'Other'
		END AS FACULTY_TYPE,
		SEF_LOAD
	FROM 
		--FIND INSTRUCTOR'S RACE
		(SELECT GROUPED_RACES.ID,
		CASE 
			WHEN RACES IS NULL THEN 'X'
			WHEN LEFT(RACES, 1) = LEFT(RACES, 3) THEN 'T'
			WHEN LEN(RACES) = '2' THEN LEFT(RACES, 1)
			ELSE 'T'	
		END RACE
		FROM
			(SELECT ID, 
				STUFF((SELECT DISTINCT ',' + CAST(PER_RACES AS VARCHAR(30))
				FROM colleague_staging.dbo.PERSON_LS PERSON2
				WHERE PERSON2.ID = PERSON1.ID
				FOR XML PATH('')),1,1,'') AS RACES
			FROM colleague_staging.dbo.PERSON_LS PERSON1
			GROUP BY ID) GROUPED_RACES
		--REMOVE HISPANIC
		LEFT JOIN 
			(SELECT DISTINCT PERSON_LS.ID, 'H' HISPANIC
			FROM colleague_staging.dbo.PERSON_LS
			WHERE PER_ETHNICS = 'HIS'
			OR PER_RACES LIKE 'H%%') HISPANIC
		ON GROUPED_RACES.ID = HISPANIC.ID
		WHERE HISPANIC IS NULL
		--PULL HISPANIC BACK IN
		UNION ALL
		SELECT DISTINCT PERSON_LS.ID, 'H' HISPANIC
		FROM colleague_staging.dbo.PERSON_LS
		WHERE PER_ETHNICS = 'HIS'
		OR PER_RACES LIKE 'H%%') RACE_ETH
	RIGHT JOIN FACULTY ON RACE_ETH.ID = FACULTY_ID
	RIGHT JOIN SECTION_FACULTY ON FACULTY_ID = SEF_FACULTY_ID
	LEFT JOIN ETHNICITY_IPEDS ON RACE = ETHNICITY_IPEDS_ID
	INNER JOIN SECTION ON SEF_SECTION_ID = SECTION_ID
	INNER JOIN TERM ON SEC_TERM = TERM_ID
	INNER JOIN COURSE ON SEC_COURSE_ID = COURSE_ID
	WHERE TER_SORT between '%s' and '%s'
	) INSTRUCTOR_ETH
GROUP BY ACADEMIC_YEAR,ETI_DESC, FACULTY_TYPE"
                           , progRecentYear
                           , maxTermSort
  )
  ethDf <- dbGetQuery(db, qEthnicityFac)
  return(ethDf)
}

# TOTAL Program Faculty Gender  -- Most recent year

progPercentFacGenderTot <- function(program, progRecentYear, maxTermSort) {
  
  qGenderFac <- sprintf("SELECT ACADEMIC_YEAR, PROGRAM, FAC_GENDER, FACULTY_TYPE, COUNT(DISTINCT FACULTY_ID) FACULTY_HEADCOUNT,   SUM(SEF_LOAD)/100 FACULTY_LOAD
	FROM (SELECT
	 CASE 
		WHEN RIGHT(TER_SORT, 1) < '3' THEN LEFT(TER_SORT,4) - 1
		ELSE LEFT(TER_SORT, 4)
		END AS ACADEMIC_YEAR,
		DEC_DESC AS PROGRAM,
    CASE
	  WHEN FAC_GENDER IS NULL OR FAC_GENDER IN(' ', 'U', 'X') THEN 'U'
	  ELSE FAC_GENDER
	  END AS FAC_GENDER,
		FACULTY_ID,
		CASE
			WHEN SEF_TEACHING_ARRANGEMENT IN ('FN','WN','XN', 'FI') THEN 'Associate'
			WHEN SEF_TEACHING_ARRANGEMENT IN ('FR', 'FL', 'FO','FV','WR','XR') THEN 'Full-Time'
			ELSE 'Other'
		END AS FACULTY_TYPE,
		SEF_LOAD
	FROM 
	FACULTY 
	INNER JOIN SECTION_FACULTY ON FACULTY_ID = SEF_FACULTY_ID
	INNER JOIN SECTION ON SEF_SECTION_ID = SECTION_ID
	INNER JOIN TERM ON SEC_TERM = TERM_ID
	INNER JOIN COURSE ON SEC_COURSE_ID = COURSE_ID
	INNER JOIN DEPARTMENT ON CRS_DEPARTMENT = DEPARTMENT_ID
	INNER JOIN DEPT_CHAIR ON DEP_DEPT_CHAIR = DEPT_CHAIR_ID
	WHERE DEPT_CHAIR_ID = '%s'
	AND TER_SORT between '%s' and '%s'
	) INSTRUCTOR_GENDER
GROUP BY ACADEMIC_YEAR, PROGRAM, FAC_GENDER, FACULTY_TYPE"
                           , program
                           , progRecentYear
                           , maxTermSort
  )
  genderDf <- dbGetQuery(db, qGenderFac)
  return(genderDf)
}

# College Total Faculty Gender  -- Most recent year
percentFacGenderCol <- function(progRecentYear, maxTermSort) {
  
  qGenderFac <- sprintf("SELECT ACADEMIC_YEAR, 'Butte College' PROGRAM, FAC_GENDER, FACULTY_TYPE, COUNT(DISTINCT FACULTY_ID)      FACULTY_HEADCOUNT, SUM(SEF_LOAD)/100 FACULTY_LOAD
	FROM (SELECT
	 CASE 
		WHEN RIGHT(TER_SORT, 1) < '3' THEN LEFT(TER_SORT,4) - 1
		ELSE LEFT(TER_SORT, 4)
		END AS ACADEMIC_YEAR,
    CASE
	  WHEN FAC_GENDER IS NULL OR FAC_GENDER IN(' ', 'U', 'X') THEN 'U'
	  ELSE FAC_GENDER
	  END AS FAC_GENDER,		
		FACULTY_ID,
		CASE
			WHEN SEF_TEACHING_ARRANGEMENT IN ('FN','WN','XN','FI') THEN 'Associate'
			WHEN SEF_TEACHING_ARRANGEMENT IN ('FR', 'FL', 'FO','FV','WR','XR') THEN 'Full-Time'
			ELSE 'Other'
		END AS FACULTY_TYPE,
		SEF_LOAD
	FROM 
  FACULTY
	INNER JOIN SECTION_FACULTY ON FACULTY_ID = SEF_FACULTY_ID
	INNER JOIN SECTION ON SEF_SECTION_ID = SECTION_ID
	INNER JOIN TERM ON SEC_TERM = TERM_ID
	INNER JOIN COURSE ON SEC_COURSE_ID = COURSE_ID
	WHERE TER_SORT between '%s' and '%s'
	) INSTRUCTOR_GENDER
GROUP BY ACADEMIC_YEAR, FAC_GENDER, FACULTY_TYPE"
                           , progRecentYear
                           , maxTermSort
  )
  genderDf <- dbGetQuery(db, qGenderFac)
  return(genderDf)
}


# TOTAL Program Faculty AGE  -- Most recent year

progPercentFacAgeTot <- function(program, progRecentYear, maxTermSort) {
  
  qAgeFac <- sprintf("SELECT ACADEMIC_YEAR, PROGRAM, FAC_AGE, FACULTY_TYPE, COUNT(DISTINCT FACULTY_ID) FACULTY_HEADCOUNT, SUM(SEF_LOAD)/100 FACULTY_LOAD
	FROM (SELECT
	 CASE 
		WHEN RIGHT(TER_SORT, 1) < '3' THEN LEFT(TER_SORT,4) - 1
		ELSE LEFT(TER_SORT, 4)
		END AS ACADEMIC_YEAR,
		DEC_DESC AS PROGRAM,
		CASE
      WHEN (CONVERT(INT, CONVERT(CHAR(8),GETDATE(),112))-CONVERT(CHAR(8),FAC_BIRTH_DATE,112))/10000 < 35 THEN '0 - 35'
      WHEN (CONVERT(INT, CONVERT(CHAR(8),GETDATE(),112))-CONVERT(CHAR(8),FAC_BIRTH_DATE,112))/10000 BETWEEN '35' AND '49' THEN           '35 - 49'
      WHEN (CONVERT(INT, CONVERT(CHAR(8),GETDATE(),112))-CONVERT(CHAR(8),FAC_BIRTH_DATE,112))/10000 BETWEEN '50' AND '65' THEN           '50 - 65'
      WHEN (CONVERT(INT, CONVERT(CHAR(8),GETDATE(),112))-CONVERT(CHAR(8),FAC_BIRTH_DATE,112))/10000 > '65' THEN '65 and Over'
      ELSE 'Unknown'
      END AS FAC_AGE,
		FACULTY_ID,
		CASE
			WHEN SEF_TEACHING_ARRANGEMENT IN ('FN','WN','XN', 'FI') THEN 'Associate'
			WHEN SEF_TEACHING_ARRANGEMENT IN ('FR', 'FL', 'FO','FV','WR','XR') THEN 'Full-Time'
			ELSE 'Other'
		END AS FACULTY_TYPE,
		SEF_LOAD
	FROM 
	FACULTY 
	INNER JOIN SECTION_FACULTY ON FACULTY_ID = SEF_FACULTY_ID
	INNER JOIN SECTION ON SEF_SECTION_ID = SECTION_ID
	INNER JOIN TERM ON SEC_TERM = TERM_ID
	INNER JOIN COURSE ON SEC_COURSE_ID = COURSE_ID
	INNER JOIN DEPARTMENT ON CRS_DEPARTMENT = DEPARTMENT_ID
	INNER JOIN DEPT_CHAIR ON DEP_DEPT_CHAIR = DEPT_CHAIR_ID
	WHERE DEPT_CHAIR_ID = '%s'
	AND TER_SORT between '%s' and '%s'
	) INSTRUCTOR_AGE
GROUP BY ACADEMIC_YEAR, PROGRAM, FAC_AGE, FACULTY_TYPE
ORDER BY FAC_AGE, FACULTY_TYPE"
                        , program
                        , progRecentYear
                        , maxTermSort
  )
  ageDf <- dbGetQuery(db, qAgeFac)
  return(ageDf)
}

# College Total Faculty Age  -- Most recent year
percentFacAgeCol <- function(progRecentYear, maxTermSort) {
  
  qAgeFac <- sprintf("SELECT ACADEMIC_YEAR, 'Butte College' PROGRAM, FAC_AGE, FACULTY_TYPE, COUNT(DISTINCT FACULTY_ID)      FACULTY_HEADCOUNT, SUM(SEF_LOAD)/100 FACULTY_LOAD
	FROM (SELECT
	 CASE 
		WHEN RIGHT(TER_SORT, 1) < '3' THEN LEFT(TER_SORT,4) - 1
		ELSE LEFT(TER_SORT, 4)
		END AS ACADEMIC_YEAR,
		CASE
      WHEN (CONVERT(INT, CONVERT(CHAR(8),GETDATE(),112))-CONVERT(CHAR(8),FAC_BIRTH_DATE,112))/10000 < 35 THEN '0 - 35'
      WHEN (CONVERT(INT, CONVERT(CHAR(8),GETDATE(),112))-CONVERT(CHAR(8),FAC_BIRTH_DATE,112))/10000 BETWEEN '35' AND '49' THEN           '35 - 49'
      WHEN (CONVERT(INT, CONVERT(CHAR(8),GETDATE(),112))-CONVERT(CHAR(8),FAC_BIRTH_DATE,112))/10000 BETWEEN '50' AND '65' THEN           '50 - 65'
      WHEN (CONVERT(INT, CONVERT(CHAR(8),GETDATE(),112))-CONVERT(CHAR(8),FAC_BIRTH_DATE,112))/10000 > '65' THEN '65 and Over'
      ELSE 'Unknown'
      END AS FAC_AGE,
		FACULTY_ID,
		CASE
			WHEN SEF_TEACHING_ARRANGEMENT IN ('FN', 'FI', 'WN', 'XN') THEN 'Associate'
			WHEN SEF_TEACHING_ARRANGEMENT IN ('FR', 'FO','FL', 'FV','WR','XR') THEN 'Full-Time'
			ELSE 'Other'
		END AS FACULTY_TYPE,
		SEF_LOAD
	FROM 
	FACULTY 
	INNER JOIN SECTION_FACULTY ON FACULTY_ID = SEF_FACULTY_ID
	INNER JOIN SECTION ON SEF_SECTION_ID = SECTION_ID
	INNER JOIN TERM ON SEC_TERM = TERM_ID
	INNER JOIN COURSE ON SEC_COURSE_ID = COURSE_ID
	WHERE TER_SORT between '%s' and '%s'
	) INSTRUCTOR_AGE
GROUP BY ACADEMIC_YEAR, FAC_AGE, FACULTY_TYPE
ORDER BY FAC_AGE, FACULTY_TYPE"
                        , progRecentYear
                        , maxTermSort
  )
  ageDf <- dbGetQuery(db, qAgeFac)
  return(ageDf)
}

#######################Program Success###########################################################

#get number of Awards in the program by type
degreeChits <- function(program, minTermSort, maxTermSort) {
  
  qDegreeChits <- sprintf("SELECT ACADEMIC_YEAR, PROGRAM, DEPARTMENT, ACP_DEG_CERT_TYPE, ACP_TITLE,
  COUNT(SDC_STUDENT_ID) AWARDS
  FROM(SELECT TER_SORT, SDC_TERM, 
  CASE 
	WHEN RIGHT(TER_SORT, 1) < '3' THEN LEFT(TER_SORT,4) - 1
	ELSE LEFT(TER_SORT, 4)
	END AS ACADEMIC_YEAR,
  DEC_DESC AS PROGRAM,
  DEP_DESC AS DEPARTMENT,
  ACP_TITLE,
  ACP_DEG_CERT_TYPE,
  SDC_STUDENT_ID
  FROM STUDENT_DEG_CERT
  INNER JOIN STUDENT ON SDC_STUDENT_ID = STUDENT_ID
  INNER JOIN ACADEMIC_PROGRAM ON SDC_ACADEMIC_PROGRAM = ACADEMIC_PROGRAM_ID
  INNER JOIN DEPARTMENT  ON ACADEMIC_PROGRAM.ACP_DEPARTMENT = DEPARTMENT_ID 
  INNER JOIN DEPT_CHAIR ON DEP_DEPT_CHAIR = DEPT_CHAIR_ID
  INNER JOIN TERM ON SDC_TERM = TERM_ID
  WHERE DEPT_CHAIR_ID = '%s'
  AND TER_SORT between '%s' and '%s') STUDENTS
  GROUP BY ACADEMIC_YEAR, PROGRAM, DEPARTMENT, ACP_DEG_CERT_TYPE, ACP_TITLE, DEPARTMENT"
                      , program
                      , minTermSort
                      , maxTermSort
  )
  DegreeChits <- dbGetQuery(db, qDegreeChits)
  return(DegreeChits)
}

#GRADE DISTRIBUTION

#get GD Data from the database for a PROGRAM
progPercentGrade <- function(program, minTermSort, maxTermSort) {
  
  qGD <- sprintf("SELECT ACADEMIC_YEAR, DEPARTMENT, GRADE, COUNT(GRADES.ENR_STUDENT_ID) HEADCOUNT
FROM (SELECT TER_SORT, ENR_TERM, 
  CASE 
	WHEN RIGHT(TER_SORT, 1) < '3' THEN LEFT(TER_SORT,4) - 1
	ELSE LEFT(TER_SORT, 4)
	END AS ACADEMIC_YEAR,
	DEC_DESC AS PROGRAM,
	DEP_DESC AS DEPARTMENT,
	ENR_STUDENT_ID,
	CASE
	WHEN ENR_GRADE IN ('FW','F', 'IF') THEN 'F'
	WHEN ENR_GRADE IN ('MW', 'W') THEN 'W'
	ELSE ENR_GRADE
	END AS GRADE
  FROM ENROLLMENT
  INNER JOIN SECTION ON ENR_SECTION_ID = SECTION_ID
  INNER JOIN COURSE ON SEC_COURSE_ID = COURSE_ID
  INNER JOIN DEPARTMENT ON CRS_DEPARTMENT = DEPARTMENT_ID
  INNER JOIN DEPT_CHAIR ON DEP_DEPT_CHAIR = DEPT_CHAIR_ID
  INNER JOIN TERM ON ENR_TERM = TERM_ID
  WHERE DEPT_CHAIR_ID = '%s'
  AND TER_SORT between '%s' and '%s'
  AND (ENR_CENSUS_REG_FLAG = 'Y' OR ENR_CURRENT_REG_FLAG = 'Y')
  AND (ENR_GRADE NOT IN ('AU','RD4', 'RD8', 'EW', 'DR') AND ENR_GRADE IS NOT NULL)) GRADES
 GROUP BY ACADEMIC_YEAR, DEPARTMENT, GRADE"
                          , program
                          , minTermSort
                          , maxTermSort
  )
  GD <- dbGetQuery(db, qGD)
  return(GD)
}

#get Ethnicity data from the database for a PROGRAM TOTAL
progPercentGDTot <- function(program, minTermSort, maxTermSort) {
  
  qGD <- sprintf("SELECT ACADEMIC_YEAR, PROGRAM, GRADE, COUNT(GRADES.ENR_STUDENT_ID) HEADCOUNT
FROM (SELECT DISTINCT TER_SORT, ENR_TERM, 
  CASE 
	WHEN RIGHT(TER_SORT, 1) < '3' THEN LEFT(TER_SORT,4) - 1
	ELSE LEFT(TER_SORT, 4)
	END AS ACADEMIC_YEAR,
	DEC_DESC AS PROGRAM,
	DEP_DESC AS DEPARTMENT,
	STU_ETHNICITY_IPEDS,
	ETI_DESC,
	CASE
	WHEN ENR_GRADE IN ('FW','F', 'IF') THEN 'F'
	WHEN ENR_GRADE IN ('MW', 'W') THEN 'W'
	ELSE ENR_GRADE
	END AS GRADE,
	ENR_STUDENT_ID
  FROM ENROLLMENT
  INNER JOIN SECTION ON ENR_SECTION_ID = SECTION_ID
  INNER JOIN COURSE ON SEC_COURSE_ID = COURSE_ID
  INNER JOIN DEPARTMENT ON CRS_DEPARTMENT = DEPARTMENT_ID
  INNER JOIN DEPT_CHAIR ON DEP_DEPT_CHAIR = DEPT_CHAIR_ID
  INNER JOIN STUDENT ON ENR_STUDENT_ID = STUDENT_ID
  LEFT JOIN ETHNICITY_IPEDS ON STU_ETHNICITY_IPEDS = ETHNICITY_IPEDS_ID
  INNER JOIN TERM ON ENR_TERM = TERM_ID
  WHERE DEPT_CHAIR_ID = '%s'
  AND TER_SORT between '%s' and '%s'
  AND (ENR_CENSUS_REG_FLAG = 'Y' OR ENR_CURRENT_REG_FLAG = 'Y')
  AND (ENR_GRADE NOT IN ('AU','RD4', 'RD8', 'EW', 'DR') AND ENR_GRADE IS NOT NULL)) GRADES
 GROUP BY ACADEMIC_YEAR, PROGRAM, GRADE"
                          , program
                          , minTermSort
                          , maxTermSort
  )
  dfGD <- dbGetQuery(db, qGD)
  return(dfGD)
}


#GRADE DISTRIBUTION BY ETHNICITY

#get GD Data from the database for a PROGRAM
progPercentEthnicityGrade <- function(program, minTermSort, maxTermSort) {
  
  qEthnicityGD <- sprintf("SELECT ACADEMIC_YEAR, DEPARTMENT, ETI_DESC, GRADE, COUNT(GRADES.ENR_STUDENT_ID) HEADCOUNT
FROM (SELECT TER_SORT, ENR_TERM, 
  CASE 
	WHEN RIGHT(TER_SORT, 1) < '3' THEN LEFT(TER_SORT,4) - 1
	ELSE LEFT(TER_SORT, 4)
	END AS ACADEMIC_YEAR,
	DEC_DESC AS PROGRAM,
	DEP_DESC AS DEPARTMENT,
	ETI_DESC,
	ENR_STUDENT_ID,
	CASE
	WHEN ENR_GRADE IN ('FW','F', 'IF') THEN 'F'
	WHEN ENR_GRADE IN ('MW', 'W') THEN 'W'
	ELSE ENR_GRADE
  FROM ENROLLMENT
  INNER JOIN SECTION ON ENR_SECTION_ID = SECTION_ID
  INNER JOIN COURSE ON SEC_COURSE_ID = COURSE_ID
  INNER JOIN DEPARTMENT ON CRS_DEPARTMENT = DEPARTMENT_ID
  INNER JOIN DEPT_CHAIR ON DEP_DEPT_CHAIR = DEPT_CHAIR_ID
  INNER JOIN STUDENT ON ENR_STUDENT_ID = STUDENT_ID
  LEFT JOIN ETHNICITY_IPEDS ON STU_ETHNICITY_IPEDS = ETHNICITY_IPEDS_ID
  INNER JOIN TERM ON ENR_TERM = TERM_ID
  WHERE DEPT_CHAIR_ID = '%s'
  AND TER_SORT between '%s' and '%s'
  AND (ENR_CENSUS_REG_FLAG = 'Y' OR ENR_CURRENT_REG_FLAG = 'Y')
  AND (ENR_GRADE NOT IN ('AU','RD4', 'RD8', 'EW', 'DR') AND ENR_GRADE IS NOT NULL)) GRADES
 GROUP BY ACADEMIC_YEAR, DEPARTMENT, ETI_DESC ENR_GRADE"
                        , program
                        , minTermSort
                        , maxTermSort
  )
  ethDfGD <- dbGetQuery(db, qEthnicityGD)
  return(ethDfGD)
}

#get Ethnicity grade distribution data from the database for a PROGRAM TOTAL
progPercentEthnicityGDTot <- function(program, minTermSort, maxTermSort) {
  
  qEthnicityGD <- sprintf("SELECT ACADEMIC_YEAR, PROGRAM, ETI_DESC,	STU_ETHNICITY_IPEDS, GRADE, COUNT(GRADES.ENR_STUDENT_ID) HEADCOUNT
FROM (SELECT DISTINCT TER_SORT, ENR_TERM, 
  CASE 
	WHEN RIGHT(TER_SORT, 1) < '3' THEN LEFT(TER_SORT,4) - 1
	ELSE LEFT(TER_SORT, 4)
	END AS ACADEMIC_YEAR,
	DEC_DESC AS PROGRAM,
	DEP_DESC AS DEPARTMENT,
	STU_ETHNICITY_IPEDS,
	ETI_DESC,
	CASE
	WHEN ENR_GRADE IN ('FW','F', 'IF') THEN 'F'
	WHEN ENR_GRADE IN ('MW', 'W') THEN 'W'
	ELSE ENR_GRADE
	END AS GRADE,
	ENR_STUDENT_ID
  FROM ENROLLMENT
  INNER JOIN SECTION ON ENR_SECTION_ID = SECTION_ID
  INNER JOIN COURSE ON SEC_COURSE_ID = COURSE_ID
  INNER JOIN DEPARTMENT ON CRS_DEPARTMENT = DEPARTMENT_ID
  INNER JOIN DEPT_CHAIR ON DEP_DEPT_CHAIR = DEPT_CHAIR_ID
  INNER JOIN STUDENT ON ENR_STUDENT_ID = STUDENT_ID
  LEFT JOIN ETHNICITY_IPEDS ON STU_ETHNICITY_IPEDS = ETHNICITY_IPEDS_ID
  INNER JOIN TERM ON ENR_TERM = TERM_ID
  WHERE DEPT_CHAIR_ID = '%s'
  AND TER_SORT between '%s' and '%s'
  AND (ENR_CENSUS_REG_FLAG = 'Y' OR ENR_CURRENT_REG_FLAG = 'Y')
  AND (ENR_GRADE NOT IN ('AU','RD4', 'RD8', 'EW', 'DR') AND ENR_GRADE IS NOT NULL)) GRADES
 GROUP BY ACADEMIC_YEAR, PROGRAM, ETI_DESC,	STU_ETHNICITY_IPEDS, GRADE"
                        , program
                        , minTermSort
                        , maxTermSort
  )
  ethDfGD <- dbGetQuery(db, qEthnicityGD)
  return(ethDfGD)
}


#get Ethnicity SUCCESS RATE DATA for DI Calculations a PROGRAM TOTAL
progPercentEthnicityDITot <- function(program, minTermSort, maxTermSort) {
  
  qEthnicityDI <- sprintf("SELECT ACADEMIC_YEAR, PROGRAM, ETI_DESC,	STU_ETHNICITY_IPEDS, SUM(GRADES.ENR_SUCCESS_NUMERATOR) SUCCESS, SUM(GRADES.ENR_SUCCESS_DENOMINATOR) TOTAL
FROM (SELECT DISTINCT TER_SORT, ENR_TERM, 
  CASE 
	WHEN RIGHT(TER_SORT, 1) < '3' THEN LEFT(TER_SORT,4) - 1
	ELSE LEFT(TER_SORT, 4)
	END AS ACADEMIC_YEAR,
	DEC_DESC AS PROGRAM,
	DEP_DESC AS DEPARTMENT,
	STU_ETHNICITY_IPEDS,
	ETI_DESC,
	ENR_SUCCESS_NUMERATOR,
	ENR_SUCCESS_DENOMINATOR,
	ENR_STUDENT_ID
  FROM ENROLLMENT
  INNER JOIN SECTION ON ENR_SECTION_ID = SECTION_ID
  INNER JOIN COURSE ON SEC_COURSE_ID = COURSE_ID
  INNER JOIN DEPARTMENT ON CRS_DEPARTMENT = DEPARTMENT_ID
  INNER JOIN DEPT_CHAIR ON DEP_DEPT_CHAIR = DEPT_CHAIR_ID
  INNER JOIN STUDENT ON ENR_STUDENT_ID = STUDENT_ID
  LEFT JOIN ETHNICITY_IPEDS ON STU_ETHNICITY_IPEDS = ETHNICITY_IPEDS_ID
  INNER JOIN TERM ON ENR_TERM = TERM_ID
  WHERE DEPT_CHAIR_ID = '%s'
  AND TER_SORT between '%s' and '%s'
  AND (ENR_CENSUS_REG_FLAG = 'Y' OR ENR_CURRENT_REG_FLAG = 'Y')) GRADES
 GROUP BY ACADEMIC_YEAR, PROGRAM, ETI_DESC,	STU_ETHNICITY_IPEDS"
                          , program
                          , minTermSort
                          , maxTermSort
  )
  ethDfDI <- dbGetQuery(db, qEthnicityDI)
  return(ethDfDI)
}

#get Group SUCCESS RATE DATA for DI Calculations a PROGRAM TOTAL
progPercentGroupDITot <- function(program, minTermSort, maxTermSort) {
  
  qGroupDI <- sprintf("SELECT ACADEMIC_YEAR, PROGRAM, LOW_INCOME, STU_DISABILITY_FLAG, VETERAN_FLAG, STU_FOSTER_YOUTH_FLAG, SUM(GRADES.ENR_SUCCESS_NUMERATOR) SUCCESS, SUM(GRADES.ENR_SUCCESS_DENOMINATOR) TOTAL
FROM (SELECT DISTINCT TER_SORT, ENR_TERM, 
  CASE 
	WHEN RIGHT(TER_SORT, 1) < '3' THEN LEFT(TER_SORT,4) - 1
	ELSE LEFT(TER_SORT, 4)
	END AS ACADEMIC_YEAR,
	DEC_DESC AS PROGRAM,
	DEP_DESC AS DEPARTMENT,
  CASE
  WHEN STU_VERIFIED_VETERAN_FLAG <> 'N' THEN 'Y'
  ELSE 'N'
  END AS VETERAN_FLAG,
  STU_FOSTER_YOUTH_FLAG,
  STU_DISABILITY_FLAG,
  CASE 
	WHEN LOW_INCOME.SFA_STUDENT_ID IS NOT NULL THEN 'Y'
	ELSE 'N'
	END AS LOW_INCOME,
	ENR_SUCCESS_NUMERATOR,
	ENR_SUCCESS_DENOMINATOR,
	ENR_STUDENT_ID
  FROM ENROLLMENT
  INNER JOIN SECTION ON ENR_SECTION_ID = SECTION_ID
  INNER JOIN COURSE ON SEC_COURSE_ID = COURSE_ID
  INNER JOIN DEPARTMENT ON CRS_DEPARTMENT = DEPARTMENT_ID
  INNER JOIN DEPT_CHAIR ON DEP_DEPT_CHAIR = DEPT_CHAIR_ID
  INNER JOIN STUDENT ON ENR_STUDENT_ID = STUDENT_ID
  LEFT JOIN (SELECT DISTINCT SFA_STUDENT_ID, SFA_AWARD_PERIOD
	  FROM STUDENT_FA_TERM_AWARD
	  WHERE SFA_AWARD LIKE ('%%BOG')
	  OR SFA_AWARD = 'PELL') LOW_INCOME ON ENR_STUDENT_ID = SFA_STUDENT_ID
	  AND ENR_TERM = SFA_AWARD_PERIOD
  INNER JOIN TERM ON ENR_TERM = TERM_ID
  WHERE DEPT_CHAIR_ID = '%s'
  AND TER_SORT between '%s' and '%s'
  AND (ENR_CENSUS_REG_FLAG = 'Y' OR ENR_CURRENT_REG_FLAG = 'Y')) GRADES
 GROUP BY ACADEMIC_YEAR, PROGRAM, LOW_INCOME, STU_DISABILITY_FLAG, VETERAN_FLAG, STU_FOSTER_YOUTH_FLAG
 HAVING LOW_INCOME = 'Y'OR STU_DISABILITY_FLAG = 'Y' OR VETERAN_FLAG = 'Y' OR STU_FOSTER_YOUTH_FLAG = 'Y'"
                          , program
                          , minTermSort
                          , maxTermSort
  )
  groupDI <- dbGetQuery(db, qGroupDI)
  return(groupDI)
}

#get Anti - Special Populations Success distribution data for DI testing from the database for a PROGRAM TOTAL
progAntiSpecPopsDITot <- function(program, minTermSort, maxTermSort) {
  qSpecPopsDI <- sprintf("SELECT ACADEMIC_YEAR, PROGRAM, LOW_INCOME, STU_DISABILITY_FLAG, VETERAN_FLAG, STU_FOSTER_YOUTH_FLAG, SUM(GRADES.ENR_SUCCESS_NUMERATOR) SUCCESS, SUM(GRADES.ENR_SUCCESS_DENOMINATOR) TOTAL
FROM (SELECT DISTINCT TER_SORT, ENR_TERM, 
  CASE 
	WHEN RIGHT(TER_SORT, 1) < '3' THEN LEFT(TER_SORT,4) - 1
	ELSE LEFT(TER_SORT, 4)
	END AS ACADEMIC_YEAR,
	DEC_DESC AS PROGRAM,
	DEP_DESC AS DEPARTMENT,
  CASE
  WHEN STU_VERIFIED_VETERAN_FLAG <> 'N' THEN 'Y'
  ELSE 'N'
  END AS VETERAN_FLAG,
  STU_FOSTER_YOUTH_FLAG,
  STU_DISABILITY_FLAG,
  CASE 
	WHEN LOW_INCOME.SFA_STUDENT_ID IS NOT NULL THEN 'Y'
	ELSE 'N'
	END AS LOW_INCOME,
	ENR_SUCCESS_NUMERATOR,
	ENR_SUCCESS_DENOMINATOR,
	ENR_STUDENT_ID
  FROM ENROLLMENT
  INNER JOIN SECTION ON ENR_SECTION_ID = SECTION_ID
  INNER JOIN COURSE ON SEC_COURSE_ID = COURSE_ID
  INNER JOIN DEPARTMENT ON CRS_DEPARTMENT = DEPARTMENT_ID
  INNER JOIN DEPT_CHAIR ON DEP_DEPT_CHAIR = DEPT_CHAIR_ID
  INNER JOIN STUDENT ON ENR_STUDENT_ID = STUDENT_ID
  LEFT JOIN (SELECT DISTINCT SFA_STUDENT_ID, SFA_AWARD_PERIOD
	  FROM STUDENT_FA_TERM_AWARD
	  WHERE SFA_AWARD LIKE ('%%BOG')
	  OR SFA_AWARD = 'PELL') LOW_INCOME ON ENR_STUDENT_ID = SFA_STUDENT_ID
	  AND ENR_TERM = SFA_AWARD_PERIOD
  INNER JOIN TERM ON ENR_TERM = TERM_ID
  WHERE DEPT_CHAIR_ID = '%s'
  AND TER_SORT between '%s' and '%s'
  AND (ENR_CENSUS_REG_FLAG = 'Y' OR ENR_CURRENT_REG_FLAG = 'Y')
  AND (ENR_GRADE NOT IN ('AU','RD4', 'RD8', 'EW', 'DR') AND ENR_GRADE IS NOT NULL)) GRADES
 GROUP BY ACADEMIC_YEAR, PROGRAM, LOW_INCOME, STU_DISABILITY_FLAG, VETERAN_FLAG, STU_FOSTER_YOUTH_FLAG
 HAVING LOW_INCOME = 'N' AND STU_DISABILITY_FLAG = 'N' AND VETERAN_FLAG = 'N' AND STU_FOSTER_YOUTH_FLAG = 'N'"
                         , program
                         , minTermSort
                         , maxTermSort
  )
  specPopsDI <- dbGetQuery(db, qSpecPopsDI)
  return(specPopsDI)
}

#get Grade distribution data by GENDER from the database for a PROGRAM TOTAL
progPercentGenderGDTot <- function(program, minTermSort, maxTermSort) {
  
  qGenderGD <- sprintf("SELECT ACADEMIC_YEAR, PROGRAM, GENDER, GRADE, COUNT(GRADES.ENR_STUDENT_ID) HEADCOUNT
FROM (SELECT DISTINCT TER_SORT, ENR_TERM, 
  CASE 
	WHEN RIGHT(TER_SORT, 1) < '3' THEN LEFT(TER_SORT,4) - 1
	ELSE LEFT(TER_SORT, 4)
	END AS ACADEMIC_YEAR,
	DEC_DESC AS PROGRAM,
	DEP_DESC AS DEPARTMENT,
    CASE
	  WHEN STU_GENDER IS NULL OR STU_GENDER IN(' ', 'U', 'X', 'B') THEN 'U'
	  ELSE STU_GENDER
	  END AS GENDER,
	CASE
	WHEN ENR_GRADE IN ('FW','F', 'IF') THEN 'F'
	WHEN ENR_GRADE IN ('MW', 'W') THEN 'W'
	ELSE ENR_GRADE
	END AS GRADE,
	ENR_STUDENT_ID
  FROM ENROLLMENT
  INNER JOIN SECTION ON ENR_SECTION_ID = SECTION_ID
  INNER JOIN COURSE ON SEC_COURSE_ID = COURSE_ID
  INNER JOIN DEPARTMENT ON CRS_DEPARTMENT = DEPARTMENT_ID
  INNER JOIN DEPT_CHAIR ON DEP_DEPT_CHAIR = DEPT_CHAIR_ID
  INNER JOIN STUDENT ON ENR_STUDENT_ID = STUDENT_ID
  LEFT JOIN ETHNICITY_IPEDS ON STU_ETHNICITY_IPEDS = ETHNICITY_IPEDS_ID
  INNER JOIN TERM ON ENR_TERM = TERM_ID
  WHERE DEPT_CHAIR_ID = '%s'
  AND TER_SORT between '%s' and '%s'
  AND (ENR_CENSUS_REG_FLAG = 'Y' OR ENR_CURRENT_REG_FLAG = 'Y')
  AND (ENR_GRADE NOT IN ('AU','RD4', 'RD8', 'EW', 'DR') AND ENR_GRADE IS NOT NULL)) GRADES
 GROUP BY ACADEMIC_YEAR, PROGRAM, GENDER, GRADE"
                          , program
                          , minTermSort
                          , maxTermSort
  )
  genderDfGD <- dbGetQuery(db, qGenderGD)
  return(genderDfGD)
}

#get Special Populations grade distribution data from the database for a PROGRAM TOTAL
progSpecPopsGDTot <- function(program, minTermSort, maxTermSort) {
  qSpecPopsGD <- sprintf("SELECT ACADEMIC_YEAR, PROGRAM, LOW_INCOME, STU_DISABILITY_FLAG, VETERAN_FLAG, STU_FOSTER_YOUTH_FLAG, GRADE, COUNT(GRADES.ENR_STUDENT_ID) HEADCOUNT
FROM (SELECT DISTINCT TER_SORT, ENR_TERM, 
  CASE 
	WHEN RIGHT(TER_SORT, 1) < '3' THEN LEFT(TER_SORT,4) - 1
	ELSE LEFT(TER_SORT, 4)
	END AS ACADEMIC_YEAR,
	DEC_DESC AS PROGRAM,
	DEP_DESC AS DEPARTMENT,
  CASE
  WHEN STU_VERIFIED_VETERAN_FLAG <> 'N' THEN 'Y'
  ELSE 'N'
  END AS VETERAN_FLAG,
  STU_FOSTER_YOUTH_FLAG,
  STU_DISABILITY_FLAG,
  CASE 
	WHEN LOW_INCOME.SFA_STUDENT_ID IS NOT NULL THEN 'Y'
	ELSE 'N'
	END AS LOW_INCOME,
	CASE
	WHEN ENR_GRADE IN ('FW','F', 'IF') THEN 'F'
	WHEN ENR_GRADE IN ('MW', 'W') THEN 'W'
	ELSE ENR_GRADE
	END AS GRADE,
	ENR_STUDENT_ID
  FROM ENROLLMENT
  INNER JOIN SECTION ON ENR_SECTION_ID = SECTION_ID
  INNER JOIN COURSE ON SEC_COURSE_ID = COURSE_ID
  INNER JOIN DEPARTMENT ON CRS_DEPARTMENT = DEPARTMENT_ID
  INNER JOIN DEPT_CHAIR ON DEP_DEPT_CHAIR = DEPT_CHAIR_ID
  INNER JOIN STUDENT ON ENR_STUDENT_ID = STUDENT_ID
  LEFT JOIN (SELECT DISTINCT SFA_STUDENT_ID, SFA_AWARD_PERIOD
	  FROM STUDENT_FA_TERM_AWARD
	  WHERE SFA_AWARD LIKE ('%%BOG')
	  OR SFA_AWARD = 'PELL') LOW_INCOME ON ENR_STUDENT_ID = SFA_STUDENT_ID
	  AND ENR_TERM = SFA_AWARD_PERIOD
  INNER JOIN TERM ON ENR_TERM = TERM_ID
  WHERE DEPT_CHAIR_ID = '%s'
  AND TER_SORT between '%s' and '%s'
  AND (ENR_CENSUS_REG_FLAG = 'Y' OR ENR_CURRENT_REG_FLAG = 'Y')
  AND (ENR_GRADE NOT IN ('AU','RD4', 'RD8', 'EW', 'DR') AND ENR_GRADE IS NOT NULL)) GRADES
 GROUP BY ACADEMIC_YEAR, PROGRAM, LOW_INCOME, STU_DISABILITY_FLAG, VETERAN_FLAG, STU_FOSTER_YOUTH_FLAG, GRADE
 HAVING LOW_INCOME = 'Y'OR STU_DISABILITY_FLAG = 'Y' OR VETERAN_FLAG = 'Y' OR STU_FOSTER_YOUTH_FLAG = 'Y'"
                          , program
                          , minTermSort
                          , maxTermSort
  )
  specPopsGD <- dbGetQuery(db, qSpecPopsGD)
  return(specPopsGD)
}

#get Anti - Special Populations grade distribution data from the database for a PROGRAM TOTAL
progAntiSpecPopsGDTot <- function(program, minTermSort, maxTermSort) {
  qSpecPopsGD <- sprintf("SELECT ACADEMIC_YEAR, PROGRAM, LOW_INCOME, STU_DISABILITY_FLAG, VETERAN_FLAG, STU_FOSTER_YOUTH_FLAG, GRADE, COUNT(GRADES.ENR_STUDENT_ID) HEADCOUNT
FROM (SELECT DISTINCT TER_SORT, ENR_TERM, 
  CASE 
	WHEN RIGHT(TER_SORT, 1) < '3' THEN LEFT(TER_SORT,4) - 1
	ELSE LEFT(TER_SORT, 4)
	END AS ACADEMIC_YEAR,
	DEC_DESC AS PROGRAM,
	DEP_DESC AS DEPARTMENT,
  CASE
  WHEN STU_VERIFIED_VETERAN_FLAG <> 'N' THEN 'Y'
  ELSE 'N'
  END AS VETERAN_FLAG,
  STU_FOSTER_YOUTH_FLAG,
  STU_DISABILITY_FLAG,
  CASE 
	WHEN LOW_INCOME.SFA_STUDENT_ID IS NOT NULL THEN 'Y'
	ELSE 'N'
	END AS LOW_INCOME,
	CASE
	WHEN ENR_GRADE IN ('FW','F', 'IF') THEN 'F'
	WHEN ENR_GRADE IN ('MW', 'W') THEN 'W'
	ELSE ENR_GRADE
	END AS GRADE,
	ENR_STUDENT_ID
  FROM ENROLLMENT
  INNER JOIN SECTION ON ENR_SECTION_ID = SECTION_ID
  INNER JOIN COURSE ON SEC_COURSE_ID = COURSE_ID
  INNER JOIN DEPARTMENT ON CRS_DEPARTMENT = DEPARTMENT_ID
  INNER JOIN DEPT_CHAIR ON DEP_DEPT_CHAIR = DEPT_CHAIR_ID
  INNER JOIN STUDENT ON ENR_STUDENT_ID = STUDENT_ID
  LEFT JOIN (SELECT DISTINCT SFA_STUDENT_ID, SFA_AWARD_PERIOD
	  FROM STUDENT_FA_TERM_AWARD
	  WHERE SFA_AWARD LIKE ('%%BOG')
	  OR SFA_AWARD = 'PELL') LOW_INCOME ON ENR_STUDENT_ID = SFA_STUDENT_ID
	  AND ENR_TERM = SFA_AWARD_PERIOD
  INNER JOIN TERM ON ENR_TERM = TERM_ID
  WHERE DEPT_CHAIR_ID = '%s'
  AND TER_SORT between '%s' and '%s'
  AND (ENR_CENSUS_REG_FLAG = 'Y' OR ENR_CURRENT_REG_FLAG = 'Y')
  AND (ENR_GRADE NOT IN ('AU','RD4', 'RD8', 'EW', 'DR') AND ENR_GRADE IS NOT NULL)) GRADES
 GROUP BY ACADEMIC_YEAR, PROGRAM, LOW_INCOME, STU_DISABILITY_FLAG, VETERAN_FLAG, STU_FOSTER_YOUTH_FLAG, GRADE
 HAVING LOW_INCOME = 'N' AND STU_DISABILITY_FLAG = 'N' AND VETERAN_FLAG = 'N' AND STU_FOSTER_YOUTH_FLAG = 'N'"
                         , program
                         , minTermSort
                         , maxTermSort
  )
  specPopsGD <- dbGetQuery(db, qSpecPopsGD)
  return(specPopsGD)
}
